-- S268 (2026-09-05): model-id fragmentation cleanup.
--
-- Adds 83 notation-variant ids to data/model_canonical_map.json so the loader rewrites them
-- on every ingest. This migration moves the already-stored rows onto the canonical id and
-- removes the now-empty duplicate model rows, which the loader cannot do on its own.
--
-- Only same-vendor notation variants are merged (prefix-less orphans, dash-vs-dot, hyphen
-- drift, and the vendor synonyms qwen/alibaba, mistralai/mistral, moonshotai/moonshot).
-- Cross-vendor pairs stay split per the S163 decision that vendor choice is subjective —
-- 81 such groups were skipped, including boltz-2 (jwohlwend/boltz-ai/mit), flux (bfl vs
-- black-forest-labs), chexagent (rad-onc vs stanford-aimi) and esm-c (biohub vs
-- evolutionaryscale).

UPDATE OR IGNORE scores SET model_id='alibaba/qwen-3.5-2b' WHERE model_id='alibaba/qwen3.5-2b';
DELETE FROM scores WHERE model_id='alibaba/qwen3.5-2b';
DELETE FROM models WHERE id='alibaba/qwen3.5-2b';
UPDATE OR IGNORE scores SET model_id='alibaba/wan2-7-image' WHERE model_id='alibaba/wan-2.7-image';
DELETE FROM scores WHERE model_id='alibaba/wan-2.7-image';
DELETE FROM models WHERE id='alibaba/wan-2.7-image';
UPDATE OR IGNORE scores SET model_id='alibaba/wan2.7-image-pro' WHERE model_id='alibaba/wan-2.7-image-pro';
DELETE FROM scores WHERE model_id='alibaba/wan-2.7-image-pro';
DELETE FROM models WHERE id='alibaba/wan-2.7-image-pro';
UPDATE OR IGNORE scores SET model_id='allenai/molmoact-2' WHERE model_id='allenai/molmoact2';
DELETE FROM scores WHERE model_id='allenai/molmoact2';
DELETE FROM models WHERE id='allenai/molmoact2';
UPDATE OR IGNORE scores SET model_id='black-forest-labs/flux-2-dev' WHERE model_id='black-forest-labs/flux.2-dev';
DELETE FROM scores WHERE model_id='black-forest-labs/flux.2-dev';
DELETE FROM models WHERE id='black-forest-labs/flux.2-dev';
UPDATE OR IGNORE scores SET model_id='black-forest-labs/flux-2-dev' WHERE model_id='black-forest-labs/flux2-dev';
DELETE FROM scores WHERE model_id='black-forest-labs/flux2-dev';
DELETE FROM models WHERE id='black-forest-labs/flux2-dev';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-reason2-8b' WHERE model_id='cosmos-reason-2-8b';
DELETE FROM scores WHERE model_id='cosmos-reason-2-8b';
DELETE FROM models WHERE id='cosmos-reason-2-8b';
UPDATE OR IGNORE scores SET model_id='deepseek/deepseek-r1-0528' WHERE model_id='deepseek-r1-0528';
DELETE FROM scores WHERE model_id='deepseek-r1-0528';
DELETE FROM models WHERE id='deepseek-r1-0528';
UPDATE OR IGNORE scores SET model_id='deepseek/deepseek-r1-distill-llama-70b' WHERE model_id='deepseek-r1-distill-llama-70b';
DELETE FROM scores WHERE model_id='deepseek-r1-distill-llama-70b';
DELETE FROM models WHERE id='deepseek-r1-distill-llama-70b';
UPDATE OR IGNORE scores SET model_id='evolutionaryscale/esm-3' WHERE model_id='evolutionaryscale/esm3';
DELETE FROM scores WHERE model_id='evolutionaryscale/esm3';
DELETE FROM models WHERE id='evolutionaryscale/esm3';
UPDATE OR IGNORE scores SET model_id='google/gemini-3.1-flash-lite' WHERE model_id='gemini-3-1-flash-lite';
DELETE FROM scores WHERE model_id='gemini-3-1-flash-lite';
DELETE FROM models WHERE id='gemini-3-1-flash-lite';
UPDATE OR IGNORE scores SET model_id='google/gemini-3.1-pro-preview' WHERE model_id='gemini-3-1-pro-preview';
DELETE FROM scores WHERE model_id='gemini-3-1-pro-preview';
DELETE FROM models WHERE id='gemini-3-1-pro-preview';
UPDATE OR IGNORE scores SET model_id='google/gemini-3.5-flash-medium' WHERE model_id='gemini-3-5-flash-medium';
DELETE FROM scores WHERE model_id='gemini-3-5-flash-medium';
DELETE FROM models WHERE id='gemini-3-5-flash-medium';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-26b-a4b' WHERE model_id='gemma-4-26b-a4b';
DELETE FROM scores WHERE model_id='gemma-4-26b-a4b';
DELETE FROM models WHERE id='gemma-4-26b-a4b';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-31b' WHERE model_id='gemma-4-31b';
DELETE FROM scores WHERE model_id='gemma-4-31b';
DELETE FROM models WHERE id='gemma-4-31b';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e2b' WHERE model_id='gemma-4-e2b';
DELETE FROM scores WHERE model_id='gemma-4-e2b';
DELETE FROM models WHERE id='gemma-4-e2b';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e4b' WHERE model_id='gemma-4-e4b';
DELETE FROM scores WHERE model_id='gemma-4-e4b';
DELETE FROM models WHERE id='gemma-4-e4b';
UPDATE OR IGNORE scores SET model_id='zhipu/glm-5.1' WHERE model_id='glm-5-1';
DELETE FROM scores WHERE model_id='glm-5-1';
DELETE FROM models WHERE id='glm-5-1';
UPDATE OR IGNORE scores SET model_id='google/gemini-2.0-flash' WHERE model_id='google/gemini-2-0-flash';
DELETE FROM scores WHERE model_id='google/gemini-2-0-flash';
DELETE FROM models WHERE id='google/gemini-2-0-flash';
UPDATE OR IGNORE scores SET model_id='google/gemini-2.5-flash' WHERE model_id='google/gemini-2-5-flash';
DELETE FROM scores WHERE model_id='google/gemini-2-5-flash';
DELETE FROM models WHERE id='google/gemini-2-5-flash';
UPDATE OR IGNORE scores SET model_id='google/gemini-2.5-pro' WHERE model_id='google/gemini-2-5-pro';
DELETE FROM scores WHERE model_id='google/gemini-2-5-pro';
DELETE FROM models WHERE id='google/gemini-2-5-pro';
UPDATE OR IGNORE scores SET model_id='google/gemini-3.1-flash-live' WHERE model_id='google/gemini-3-1-flash-live';
DELETE FROM scores WHERE model_id='google/gemini-3-1-flash-live';
DELETE FROM models WHERE id='google/gemini-3-1-flash-live';
UPDATE OR IGNORE scores SET model_id='google/gemini-3.1-pro-preview' WHERE model_id='google/gemini-3-1-pro-preview';
DELETE FROM scores WHERE model_id='google/gemini-3-1-pro-preview';
DELETE FROM models WHERE id='google/gemini-3-1-pro-preview';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-12b-it-qat-q4_0-gguf' WHERE model_id='google/gemma-4-12b-it-qat-q4-0-gguf';
DELETE FROM scores WHERE model_id='google/gemma-4-12b-it-qat-q4-0-gguf';
DELETE FROM models WHERE id='google/gemma-4-12b-it-qat-q4-0-gguf';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-26b-a4b-it-qat-q4_0-gguf' WHERE model_id='google/gemma-4-26b-a4b-it-qat-q4-0-gguf';
DELETE FROM scores WHERE model_id='google/gemma-4-26b-a4b-it-qat-q4-0-gguf';
DELETE FROM models WHERE id='google/gemma-4-26b-a4b-it-qat-q4-0-gguf';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-31b-it-qat-q4_0-gguf' WHERE model_id='google/gemma-4-31b-it-qat-q4-0-gguf';
DELETE FROM scores WHERE model_id='google/gemma-4-31b-it-qat-q4-0-gguf';
DELETE FROM models WHERE id='google/gemma-4-31b-it-qat-q4-0-gguf';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e2b-it-qat-q4_0-gguf' WHERE model_id='google/gemma-4-e2b-it-qat-q4-0-gguf';
DELETE FROM scores WHERE model_id='google/gemma-4-e2b-it-qat-q4-0-gguf';
DELETE FROM models WHERE id='google/gemma-4-e2b-it-qat-q4-0-gguf';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e4b-it-qat-q4_0-gguf' WHERE model_id='google/gemma-4-e4b-it-qat-q4-0-gguf';
DELETE FROM scores WHERE model_id='google/gemma-4-e4b-it-qat-q4-0-gguf';
DELETE FROM models WHERE id='google/gemma-4-e4b-it-qat-q4-0-gguf';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-31b' WHERE model_id='google/gemma4-31b';
DELETE FROM scores WHERE model_id='google/gemma4-31b';
DELETE FROM models WHERE id='google/gemma4-31b';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e2b' WHERE model_id='google/gemma4-e2b';
DELETE FROM scores WHERE model_id='google/gemma4-e2b';
DELETE FROM models WHERE id='google/gemma4-e2b';
UPDATE OR IGNORE scores SET model_id='google/gemma-4-e4b' WHERE model_id='google/gemma4-e4b';
DELETE FROM scores WHERE model_id='google/gemma4-e4b';
DELETE FROM models WHERE id='google/gemma4-e4b';
UPDATE OR IGNORE scores SET model_id='openai/gpt-5.2' WHERE model_id='gpt-5-2';
DELETE FROM scores WHERE model_id='gpt-5-2';
DELETE FROM models WHERE id='gpt-5-2';
UPDATE OR IGNORE scores SET model_id='openai/gpt-5.2-chat-latest' WHERE model_id='gpt-5-2-chat-latest';
DELETE FROM scores WHERE model_id='gpt-5-2-chat-latest';
DELETE FROM models WHERE id='gpt-5-2-chat-latest';
UPDATE OR IGNORE scores SET model_id='openai/gpt-5.4-pro-xhigh' WHERE model_id='gpt-5-4-pro-xhigh';
DELETE FROM scores WHERE model_id='gpt-5-4-pro-xhigh';
DELETE FROM models WHERE id='gpt-5-4-pro-xhigh';
UPDATE OR IGNORE scores SET model_id='openai/gpt-5.5-medium' WHERE model_id='gpt-5-5-medium';
DELETE FROM scores WHERE model_id='gpt-5-5-medium';
DELETE FROM models WHERE id='gpt-5-5-medium';
UPDATE OR IGNORE scores SET model_id='openai/gpt-5.5-pro' WHERE model_id='gpt-5-5-pro';
DELETE FROM scores WHERE model_id='gpt-5-5-pro';
DELETE FROM models WHERE id='gpt-5-5-pro';
UPDATE OR IGNORE scores SET model_id='microsoft/mai-transcribe-1-5' WHERE model_id='microsoft/mai-transcribe-1.5';
DELETE FROM scores WHERE model_id='microsoft/mai-transcribe-1.5';
DELETE FROM models WHERE id='microsoft/mai-transcribe-1.5';
UPDATE OR IGNORE scores SET model_id='xiaomi/mimo-v2.5-pro' WHERE model_id='mimo-v2-5-pro';
DELETE FROM scores WHERE model_id='mimo-v2-5-pro';
DELETE FROM models WHERE id='mimo-v2-5-pro';
UPDATE OR IGNORE scores SET model_id='mistral/mistral-large-2411' WHERE model_id='mistral/mistral-large-24.11';
DELETE FROM scores WHERE model_id='mistral/mistral-large-24.11';
DELETE FROM models WHERE id='mistral/mistral-large-24.11';
UPDATE OR IGNORE scores SET model_id='mistral/ministral-14b' WHERE model_id='mistralai/ministral-14b';
DELETE FROM scores WHERE model_id='mistralai/ministral-14b';
DELETE FROM models WHERE id='mistralai/ministral-14b';
UPDATE OR IGNORE scores SET model_id='mistral/ministral-8b-instruct-2410' WHERE model_id='mistralai/ministral-8b-instruct-2410';
DELETE FROM scores WHERE model_id='mistralai/ministral-8b-instruct-2410';
DELETE FROM models WHERE id='mistralai/ministral-8b-instruct-2410';
UPDATE OR IGNORE scores SET model_id='mistral/mistral-ocr-3' WHERE model_id='mistralai/mistral-ocr-3';
DELETE FROM scores WHERE model_id='mistralai/mistral-ocr-3';
DELETE FROM models WHERE id='mistralai/mistral-ocr-3';
UPDATE OR IGNORE scores SET model_id='mistral/pixtral-large' WHERE model_id='mistralai/pixtral-large';
DELETE FROM scores WHERE model_id='mistralai/pixtral-large';
DELETE FROM models WHERE id='mistralai/pixtral-large';
UPDATE OR IGNORE scores SET model_id='novasearch/stella-en-1.5b-v5' WHERE model_id='novasearch/stella_en_1.5b_v5';
DELETE FROM scores WHERE model_id='novasearch/stella_en_1.5b_v5';
DELETE FROM models WHERE id='novasearch/stella_en_1.5b_v5';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos3-super-image2video' WHERE model_id='nvidia/cosmos-3-super-image2video';
DELETE FROM scores WHERE model_id='nvidia/cosmos-3-super-image2video';
DELETE FROM models WHERE id='nvidia/cosmos-3-super-image2video';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-predict-1-7b' WHERE model_id='nvidia/cosmos-predict1-7b';
DELETE FROM scores WHERE model_id='nvidia/cosmos-predict1-7b';
DELETE FROM models WHERE id='nvidia/cosmos-predict1-7b';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-predict-2.5-14b' WHERE model_id='nvidia/cosmos-predict2.5-14b';
DELETE FROM scores WHERE model_id='nvidia/cosmos-predict2.5-14b';
DELETE FROM models WHERE id='nvidia/cosmos-predict2.5-14b';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-predict-2.5-2b' WHERE model_id='nvidia/cosmos-predict2.5-2b';
DELETE FROM scores WHERE model_id='nvidia/cosmos-predict2.5-2b';
DELETE FROM models WHERE id='nvidia/cosmos-predict2.5-2b';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-transfer2.5' WHERE model_id='nvidia/cosmos-transfer-2.5';
DELETE FROM scores WHERE model_id='nvidia/cosmos-transfer-2.5';
DELETE FROM models WHERE id='nvidia/cosmos-transfer-2.5';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-3-edge' WHERE model_id='nvidia/cosmos3-edge';
DELETE FROM scores WHERE model_id='nvidia/cosmos3-edge';
DELETE FROM models WHERE id='nvidia/cosmos3-edge';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-3-nano' WHERE model_id='nvidia/cosmos3-nano';
DELETE FROM scores WHERE model_id='nvidia/cosmos3-nano';
DELETE FROM models WHERE id='nvidia/cosmos3-nano';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-3-nano-policy-droid' WHERE model_id='nvidia/cosmos3-nano-policy-droid';
DELETE FROM scores WHERE model_id='nvidia/cosmos3-nano-policy-droid';
DELETE FROM models WHERE id='nvidia/cosmos3-nano-policy-droid';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-3-super' WHERE model_id='nvidia/cosmos3-super';
DELETE FROM scores WHERE model_id='nvidia/cosmos3-super';
DELETE FROM models WHERE id='nvidia/cosmos3-super';
UPDATE OR IGNORE scores SET model_id='nvidia/cosmos-3-super-text2image' WHERE model_id='nvidia/cosmos3-super-text2image';
DELETE FROM scores WHERE model_id='nvidia/cosmos3-super-text2image';
DELETE FROM models WHERE id='nvidia/cosmos3-super-text2image';
UPDATE OR IGNORE scores SET model_id='openbmb/minicpm3-4b' WHERE model_id='openbmb/minicpm-3-4b';
DELETE FROM scores WHERE model_id='openbmb/minicpm-3-4b';
DELETE FROM models WHERE id='openbmb/minicpm-3-4b';
UPDATE OR IGNORE scores SET model_id='openbmb/minicpm-5-1b' WHERE model_id='openbmb/minicpm5-1b';
DELETE FROM scores WHERE model_id='openbmb/minicpm5-1b';
DELETE FROM models WHERE id='openbmb/minicpm5-1b';
UPDATE OR IGNORE scores SET model_id='opendatalab/mineru-2.5' WHERE model_id='opendatalab/mineru2.5';
DELETE FROM scores WHERE model_id='opendatalab/mineru2.5';
DELETE FROM models WHERE id='opendatalab/mineru2.5';
UPDATE OR IGNORE scores SET model_id='opendatalab/mineru-2.5-pro' WHERE model_id='opendatalab/mineru2.5-pro';
DELETE FROM scores WHERE model_id='opendatalab/mineru2.5-pro';
DELETE FROM models WHERE id='opendatalab/mineru2.5-pro';
UPDATE OR IGNORE scores SET model_id='openfold/openfold-3' WHERE model_id='openfold/openfold3';
DELETE FROM scores WHERE model_id='openfold/openfold3';
DELETE FROM models WHERE id='openfold/openfold3';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.6-35b-a3b' WHERE model_id='qwen-3.6-35b-a3b';
DELETE FROM scores WHERE model_id='qwen-3.6-35b-a3b';
DELETE FROM models WHERE id='qwen-3.6-35b-a3b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3-235b-a22b' WHERE model_id='qwen/qwen3-235b-a22b';
DELETE FROM scores WHERE model_id='qwen/qwen3-235b-a22b';
DELETE FROM models WHERE id='qwen/qwen3-235b-a22b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3-embedding-0.6b' WHERE model_id='qwen/qwen3-embedding-0.6b';
DELETE FROM scores WHERE model_id='qwen/qwen3-embedding-0.6b';
DELETE FROM models WHERE id='qwen/qwen3-embedding-0.6b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3-embedding-4b' WHERE model_id='qwen/qwen3-embedding-4b';
DELETE FROM scores WHERE model_id='qwen/qwen3-embedding-4b';
DELETE FROM models WHERE id='qwen/qwen3-embedding-4b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3-embedding-8b' WHERE model_id='qwen/qwen3-embedding-8b';
DELETE FROM scores WHERE model_id='qwen/qwen3-embedding-8b';
DELETE FROM models WHERE id='qwen/qwen3-embedding-8b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.5-397b-a17b' WHERE model_id='qwen/qwen3.5-397b-a17b';
DELETE FROM scores WHERE model_id='qwen/qwen3.5-397b-a17b';
DELETE FROM models WHERE id='qwen/qwen3.5-397b-a17b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.6-27b' WHERE model_id='qwen/qwen3.6-27b';
DELETE FROM scores WHERE model_id='qwen/qwen3.6-27b';
DELETE FROM models WHERE id='qwen/qwen3.6-27b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.6-35b-a3b' WHERE model_id='qwen/qwen3.6-35b-a3b';
DELETE FROM scores WHERE model_id='qwen/qwen3.6-35b-a3b';
DELETE FROM models WHERE id='qwen/qwen3.6-35b-a3b';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.6-plus' WHERE model_id='qwen/qwen3.6-plus';
DELETE FROM scores WHERE model_id='qwen/qwen3.6-plus';
DELETE FROM models WHERE id='qwen/qwen3.6-plus';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.7-max' WHERE model_id='qwen/qwen3.7-max';
DELETE FROM scores WHERE model_id='qwen/qwen3.7-max';
DELETE FROM models WHERE id='qwen/qwen3.7-max';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen2.5-72b-instruct' WHERE model_id='qwen2.5-72b-instruct';
DELETE FROM scores WHERE model_id='qwen2.5-72b-instruct';
DELETE FROM models WHERE id='qwen2.5-72b-instruct';
UPDATE OR IGNORE scores SET model_id='alibaba/qwen3.6-27b' WHERE model_id='qwen3-6-27b';
DELETE FROM scores WHERE model_id='qwen3-6-27b';
DELETE FROM models WHERE id='qwen3-6-27b';
UPDATE OR IGNORE scores SET model_id='rakuten/rakutenai-2.0-8x7b-instruct' WHERE model_id='rakuten/rakuten-ai-2.0-8x7b-instruct';
DELETE FROM scores WHERE model_id='rakuten/rakuten-ai-2.0-8x7b-instruct';
DELETE FROM models WHERE id='rakuten/rakuten-ai-2.0-8x7b-instruct';
UPDATE OR IGNORE scores SET model_id='rakuten/rakutenai-3.0' WHERE model_id='rakuten/rakuten-ai-3.0';
DELETE FROM scores WHERE model_id='rakuten/rakuten-ai-3.0';
DELETE FROM models WHERE id='rakuten/rakuten-ai-3.0';
UPDATE OR IGNORE scores SET model_id='runway/gen4-aleph' WHERE model_id='runway/gen-4-aleph';
DELETE FROM scores WHERE model_id='runway/gen-4-aleph';
DELETE FROM models WHERE id='runway/gen-4-aleph';
UPDATE OR IGNORE scores SET model_id='salesforce/moirai-1.0-r-large' WHERE model_id='salesforce/moirai-1-0-R-large';
DELETE FROM scores WHERE model_id='salesforce/moirai-1-0-R-large';
DELETE FROM models WHERE id='salesforce/moirai-1-0-R-large';
UPDATE OR IGNORE scores SET model_id='stabilityai/stable-audio-2-5' WHERE model_id='stabilityai/stable-audio-2.5';
DELETE FROM scores WHERE model_id='stabilityai/stable-audio-2.5';
DELETE FROM models WHERE id='stabilityai/stable-audio-2.5';
UPDATE OR IGNORE scores SET model_id='suno/suno-v5.5' WHERE model_id='suno/suno-v5-5';
DELETE FROM scores WHERE model_id='suno/suno-v5-5';
DELETE FROM models WHERE id='suno/suno-v5-5';
UPDATE OR IGNORE scores SET model_id='tencent/hunyuanvideo-1.5' WHERE model_id='tencent/hunyuan-video-1.5';
DELETE FROM scores WHERE model_id='tencent/hunyuan-video-1.5';
DELETE FROM models WHERE id='tencent/hunyuan-video-1.5';
UPDATE OR IGNORE scores SET model_id='tencent/hunyuan-video' WHERE model_id='tencent/hunyuanvideo';
DELETE FROM scores WHERE model_id='tencent/hunyuanvideo';
DELETE FROM models WHERE id='tencent/hunyuanvideo';
UPDATE OR IGNORE scores SET model_id='xai/grok-4.1-fast' WHERE model_id='xai/grok-4-1-fast';
DELETE FROM scores WHERE model_id='xai/grok-4-1-fast';
DELETE FROM models WHERE id='xai/grok-4-1-fast';
UPDATE OR IGNORE scores SET model_id='zhipu/glm-4.6' WHERE model_id='zhipu/glm-4-6';
DELETE FROM scores WHERE model_id='zhipu/glm-4-6';
DELETE FROM models WHERE id='zhipu/glm-4-6';
UPDATE OR IGNORE scores SET model_id='zhipu/glm-4.7' WHERE model_id='zhipu/glm-4-7';
DELETE FROM scores WHERE model_id='zhipu/glm-4-7';
DELETE FROM models WHERE id='zhipu/glm-4-7';
UPDATE OR IGNORE scores SET model_id='zhipu/glm-5.1' WHERE model_id='zhipu/glm-5-1';
DELETE FROM scores WHERE model_id='zhipu/glm-5-1';
DELETE FROM models WHERE id='zhipu/glm-5-1';
