/**
 * Bots tab (S302) — always-on personal / work AI agent products ("bots"): an agent with its own cloud computer that
 * signs into your apps, works in the background 24/7, keeps memory, runs schedules and asks before sensitive actions.
 * Sections: 1. what a bot is  2. launch timeline  3. feature matrix  4. engine models behind each bot
 *           5. product benchmark results  6. benchmark catalogue  7. sources
 * Product facts live in BOTS_DATA (generated by the S302 build from evidence-checked reader output — do not hand-edit
 * between the GENERATED markers). Scores come from the App score index. All text via textContent.
 */
var Bots = {
    _initialized: false,
    _charts: [],
    // GENERATED:BOTS_DATA:START
    BOTS_DATA: {
     "products": [
      {
       "id": "xai/grok-bot",
       "name": "Grok Bot",
       "vendor": "SpaceXAI (xAI + Cursor/Anysphere)",
       "vendor_key": "spacexai",
       "url": "https://web.archive.org/web/2026/https://x.ai/news/grok-bot-more-plans",
       "launch_date": "2026-08-11",
       "status": "beta",
       "models": "xAI first-party models (Grok 4.x; Grok 4.7 'trained to natively understand the Grok Bot harness'), third-party models from providers on Cursor's sub-processor list (unnamed; no model picker)",
       "model_ids": [
        "xai/grok-4.7"
       ],
       "own_computer": "one persistent cloud computer per user (browser, filesystem, terminal) shared by all of that user's Bots; Cursor-hosted, runs in the US",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "Bots keep context across conversations, learn preferences, learn from each other; Team Bots share expertise with per-person private memory",
       "approvals": "per-action approvals (Allow once / Always allow / Deny), 'Ask first' rules, Auto Review (independent review model for risky actions; Enterprise can enforce)",
       "platforms": "macOS, Windows, Linux, iOS, Android (secondary source only: OrcaRouter, 2026-09-02)",
       "pricing": "No standalone price: included with SuperGrok / SuperGrok Plus / SuperGrok Heavy, X Premium+ (link), Cursor Pro / Pro+ / Ultra, Cursor Teams Standard & Premium, Enterprise; weekly usage included, extra usage billed on token cost (on-demand via Cursor); free trial = usage credit with 7-day window. Dollar prices of the underlying plans only in secondary source (OrcaRouter: SuperGrok $30, Plus $100, Heavy $300; Cursor Pro $20, Pro+ $60, Ultra $200; Teams $40-$120/seat).",
       "availability": "Beta launched 2026-08-11 for top tiers; 2026-08-26 expanded to all SuperGrok, Cursor Pro and Cursor Teams plans; Enterprise 2026-09-03 (x.ai/bot FAQ now says 'generally available for Enterprise'); Team Bots 2026-09-28; computers run in the United States",
       "seed": true
      },
      {
       "id": "meta/muse",
       "name": "Muse",
       "vendor": "Meta (Meta Superintelligence Labs)",
       "vendor_key": "meta",
       "url": "https://research.meta.ai/blog/how-we-built-safety-into-muse (via security.muse.ai)",
       "launch_date": "2026-09-08",
       "status": null,
       "models": "meta/muse-spark-1.3 (Muse Spark)",
       "model_ids": [
        "meta/muse-spark-1.3"
       ],
       "own_computer": "Muse Secure VM: dedicated cloud VM with its own browser (agent + user data); separate Sentinel agent gates all internet egress; Muse Confidential VM (user-held key) later in 2026",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": "remembers what matters to a person, acts on details mentioned once; user can tell it to 'forget'",
       "approvals": "asks before sensitive actions (sending email, purchases); complete audit trail of done/planned actions; small-business: nothing publishes, sends, or spends without approval",
       "platforms": "iOS, Android, web (muse.ai), macOS (Muse for Mac), WhatsApp, AI glasses (coming), Muse Charm device (announced)",
       "pricing": "Free for most needs, with subscription plans (names/prices not on primary pages; secondary: Power $20/mo, Max $100/mo)",
       "availability": "US at launch (rolling out on iOS, Android, muse.ai); Muse for Small Business post says US and Canada",
       "seed": true
      },
      {
       "id": "openai/chatgpt-dots",
       "name": "ChatGPT dots",
       "vendor": "OpenAI",
       "vendor_key": "openai",
       "url": "https://web.archive.org/web/2026/https://openai.com/index/introducing-dots/",
       "launch_date": "2026-09-29",
       "status": null,
       "models": "openai/gpt-6-astra",
       "model_ids": [
        "openai/gpt-6-astra"
       ],
       "own_computer": "each dot has its own cloud computer and browser (sandboxed Linux + Chrome); optional connection to the user's own computer (off by default)",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "starts from ChatGPT memory and creates its own memories, incl. from connected apps; 'proactive research' notes",
       "approvals": "built-in rules + Custom Rules (allow / require approval / block); auto-review of account-affecting or sharing actions; purchases need approval; password changes always user",
       "platforms": "ChatGPT web, ChatGPT desktop (macOS, Windows), ChatGPT mobile (after desktop setup), Slack, Microsoft Teams, texting (limited beta, US Pro)",
       "pricing": "First dot included in ChatGPT Pro or Business Premium at no extra cost (plus a deeper-work allowance, extended limits first month); conversations don't count toward ChatGPT usage limits; more dots/speed to be sold later",
       "availability": "Rolling out to Pro (excluding EEA, Switzerland, UK) and Business Premium (all supported regions); Enterprise/Edu/Healthcare beta via admin (off by default); specialist dots = enterprise pilots",
       "seed": true
      },
      {
       "id": "google/gemini-spark",
       "name": "Gemini Spark",
       "vendor": "Google",
       "vendor_key": "google",
       "url": "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
       "launch_date": "2026-05-19",
       "status": "beta",
       "models": "Gemini 3.5 (Antigravity harness)",
       "model_ids": [],
       "own_computer": "cloud-based agent on Google's secure cloud infrastructure with live web browsing (no dedicated VM described)",
       "background_24x7": true,
       "multi_agent": null,
       "schedules_routines": true,
       "memory": null,
       "approvals": "designed to check with the user before major / high-stakes actions such as spending money or sending emails; opt-in",
       "platforms": "Gemini app web, Android, iOS, macOS (Gemini app for Mac, incl. remote control)",
       "pricing": "Requires Google AI Pro or Ultra subscription (not on free / AI Plus per secondary); no Spark-specific price",
       "availability": "I/O 2026-05-19: trusted testers, then Beta for US Google AI Ultra; later US Pro, then Ultra/Pro wherever Gemini Apps are supported except EEA, Nigeria, Switzerland, UK; 18+; select business users",
       "seed": true
      },
      {
       "id": "google/gemini-agent",
       "name": "Gemini agent (Gemini Enterprise / Gemini at Work 2026)",
       "vendor": "Google Cloud",
       "vendor_key": "google",
       "url": "https://cloud.google.com/blog/products/ai-machine-learning/welcome-to-gemini-at-work-2026",
       "launch_date": "2026-10-09",
       "status": null,
       "models": "Gemini family (Argon, Flash, Omni, Gemma), Claude models from Anthropic (multi-model orchestration / Smart Routing)",
       "model_ids": [
        "google/gemini-4-argon"
       ],
       "own_computer": "runs in the cloud; tasks execute inside an Agent Sandbox with its own network boundary; VMs spun up to run code carry the agent identity",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "session, semantic, procedural and episodic memory; one personalization graph across devices",
       "approvals": "role-based permissions approved by security admins; OAuth identity propagation; every action audited and attributed to the agent; Agent Gateway AI firewall enforces org policies",
       "platforms": "web, iOS, Android, Windows, macOS, command line, Google Workspace (inline in Gmail, Drive, Docs, Slides, Sheets, Chat, Calendar), Microsoft 365, Slack, headless / API",
       "pricing": "Not stated in the launch post; real-time per-project spend caps in Cloud Billing; Gemini Enterprise app editions (pre-launch page, 2026-10-05 snapshot): Business from $21/seat/mo, Standard/Plus from $30/seat/mo, pay-as-you-go $0 seat fee — relation to the Gemini agent not stated",
       "availability": "Availability/GA not stated in the post; industry versions in preview for Financial Services and Legal, coming to Government, Healthcare, Retail",
       "seed": true
      },
      {
       "id": "anthropic/claude-cowork",
       "name": "Claude Cowork (now merged into Claude)",
       "vendor": "Anthropic",
       "vendor_key": "anthropic",
       "url": "https://support.claude.com/en/articles/12138966-release-notes",
       "launch_date": "2026-01-12",
       "status": "GA",
       "models": null,
       "model_ids": [],
       "own_computer": "isolated VM locally (Desktop) + remote cloud sessions (beta, since 2026-07-07) + built-in browser in Cowork side panel",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "Memory across chat and Cowork in the cloud (2026-08-25), editable Topics",
       "approvals": "Deleting anything needs approval; optional permission mode shows plan and waits for approval before significant actions",
       "platforms": null,
       "pricing": "Pro $17/mo annual ($20 monthly); Max 5x $100/mo; Max 20x $200/mo; Team $20/seat/mo; Enterprise",
       "availability": "Paid plans; web/mobile rolling out from Max; merged into one Claude experience 2026-09-16 (Pro/Max first)",
       "seed": false
      },
      {
       "id": "microsoft/copilot-autopilot",
       "name": "Microsoft Autopilot (previously Microsoft Scout)",
       "vendor": "Microsoft",
       "vendor_key": "microsoft",
       "url": "https://www.microsoft.com/en-us/copilot/blog/2026/06/02/introducing-microsoft-scout-your-always-on-personal-agent/",
       "launch_date": "2026-06-02",
       "status": "preview",
       "models": "Work IQ / Microsoft IQ grounding; agentic work runs on usage-based billing with frontier models (Astra, Fable named)",
       "model_ids": [
        "openai/gpt-6-astra"
       ],
       "own_computer": "cloud-hosted; 'its own identity, memory, computer and workspace' in the tenant",
       "background_24x7": true,
       "multi_agent": null,
       "schedules_routines": true,
       "memory": null,
       "approvals": "Sensitive actions can require human sign-off; Purview DLP enforced",
       "platforms": null,
       "pricing": "Usage-based billing (UBB) for Cowork, Code and Autopilot",
       "availability": "Experimental release via Frontier program + private preview (Frontier enrollment, Intune policy, opt-in; GitHub Copilot license to install); private preview expansion end of Sep 2026",
       "seed": false
      },
      {
       "id": "microsoft/copilot-cowork",
       "name": "Microsoft 365 Copilot Cowork",
       "vendor": "Microsoft",
       "vendor_key": "microsoft",
       "url": "https://www.microsoft.com/en-us/copilot/blog/2026/03/09/copilot-cowork-a-new-way-of-getting-work-done/",
       "launch_date": null,
       "status": "preview",
       "models": "Claude Cowork technology (Anthropic) inside multi-model Copilot",
       "model_ids": [],
       "own_computer": "protected, sandboxed cloud environment",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": "Recommended actions shown and approved before applied; checkpoints, pause anytime",
       "platforms": null,
       "pricing": "Usage-based billing (UBB)",
       "availability": null,
       "seed": false
      },
      {
       "id": "microsoft/copilot-tasks",
       "name": "Microsoft Copilot Tasks (consumer; migrating to Copilot Cowork)",
       "vendor": "Microsoft",
       "vendor_key": "microsoft",
       "url": "https://support.microsoft.com/en-us/microsoft-copilot/using-copilot-tasks",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "cloud browser run by Copilot (clicks, scrolls, types); user can take control",
       "background_24x7": null,
       "multi_agent": null,
       "schedules_routines": true,
       "memory": "Task-specific memory (deletable)",
       "approvals": "Approval / hand-back for account-altering actions, payments, submitting personal info; approvals for recurring tasks collected at setup",
       "platforms": null,
       "pricing": null,
       "availability": "Personal Microsoft accounts; being migrated to Copilot Cowork",
       "seed": false
      },
      {
       "id": "moonshot/kimi-claw",
       "name": "Kimi Claw",
       "vendor": "Moonshot AI",
       "vendor_key": "moonshot",
       "url": "https://www.kimi.com/en-cn/help/agent/agent-overview",
       "launch_date": "2026-02",
       "status": null,
       "models": null,
       "model_ids": [
        "moonshot/kimi-k2.6"
       ],
       "own_computer": "cloud server deployment (isolated data) or local/Android; 40 GB cloud storage",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "Long-term memory, configurable personas",
       "approvals": null,
       "platforms": "web, cloud server, desktop (local), Android phone, Feishu, WeChat, WeCom, Weibo",
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "manus-ai/manus",
       "name": "Manus 2.0 (Cascade harness, Cloud Computer, Automations, Manus Studio)",
       "vendor": "Manus",
       "vendor_key": "manus",
       "url": "https://manus.im/blog",
       "launch_date": "2026-09-28",
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "cloud sandbox per task + purchasable dedicated Cloud Computer; Computer Use on the user's own computer",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": "Computer Use only in connected and authorized sessions with approved files/apps",
       "platforms": "web, desktop (Manus Studio), mobile",
       "pricing": null,
       "availability": "web, desktop, mobile; Manus resumed independent operations 2026-09-01 after Meta deal unwound",
       "seed": false
      },
      {
       "id": "manus-ai/cue",
       "name": "Cue (Manus personal-agents app)",
       "vendor": "Manus",
       "vendor_key": "manus",
       "url": "https://manus.im/blog/introducing-manus-2-0",
       "launch_date": "2026-09-28",
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "each agent has its own computer, email, phone number and wallet",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": "web, desktop, mobile, iOS (pending App Store review)",
       "pricing": "Free in early access with invite code",
       "availability": null,
       "seed": false
      },
      {
       "id": "perplexity/perplexity-computer",
       "name": "Perplexity Computer",
       "vendor": "Perplexity",
       "vendor_key": "perplexity",
       "url": "https://web.archive.org/web/2026/https://www.perplexity.ai/hub/blog/introducing-perplexity-computer",
       "launch_date": "2026-02-25",
       "status": null,
       "models": "anthropic/claude-opus-4.6 (core reasoning, at launch), Gemini (deep research sub-agents), Nano Banana, Veo 3.1, Grok, ChatGPT 5.2",
       "model_ids": [
        "anthropic/claude-opus-4.6"
       ],
       "own_computer": "isolated compute environment per task with real filesystem, real browser, tool integrations",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": "persistent memory (Perplexity platform)",
       "approvals": null,
       "platforms": null,
       "pricing": null,
       "availability": "Perplexity Max; Enterprise Max later",
       "seed": false
      },
      {
       "id": "notion/custom-agents",
       "name": "Notion Custom Agents",
       "vendor": "Notion",
       "vendor_key": "notion",
       "url": "https://www.notion.com/releases/2026-02-24",
       "launch_date": "2026-02-24",
       "status": null,
       "models": "user-selectable AI model",
       "model_ids": [],
       "own_computer": null,
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": "admin-controlled permissions, on/off controls; logged, reversible runs",
       "platforms": null,
       "pricing": "Free through 2026-05-03; from 2026-05-04 consumes Notion Credits (add-on for Business/Enterprise)",
       "availability": null,
       "seed": false
      },
      {
       "id": "opera/opera-neon",
       "name": "Opera Neon (agentic browser: Neon Do + agents)",
       "vendor": "Opera",
       "vendor_key": "opera",
       "url": "https://press.opera.com/?p=3715",
       "launch_date": "2025-09-30",
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "none for Neon Do (runs locally inside the user's logged-in browser session)",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": "pauses for user interaction; user can pause/guide/take control at any moment",
       "platforms": null,
       "pricing": "premium subscription (price not on captured pages)",
       "availability": null,
       "seed": false
      },
      {
       "id": "genspark/genspark-claw",
       "name": "Genspark Claw ('AI employee') + Genspark Cloud Computer",
       "vendor": "Genspark (MainFunc)",
       "vendor_key": "genspark",
       "url": "https://mainfunc.ai/blog",
       "launch_date": "2026-03-12",
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "dedicated per-user Genspark Cloud Computer (always-on, isolated) + Computer Use/Browser Use on local desktop",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "SecondBrain persistent memory layer (Workspace 6.0, 2026-07-20)",
       "approvals": null,
       "platforms": "web, desktop (Claw for Desktop, Workspace 4.0), WhatsApp, Telegram, Teams, Slack, Microsoft Office plugins",
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "openclaw/openclaw",
       "name": "OpenClaw (formerly Clawdbot / Moltbot) — self-hosted personal agent",
       "vendor": "OpenClaw Foundation (open source)",
       "vendor_key": "openclaw",
       "url": "https://github.com/openclaw/openclaw",
       "launch_date": null,
       "status": null,
       "models": "any: Claude, Codex, local models as swappable plugins",
       "model_ids": [],
       "own_computer": "runs on the user's own machine/server (Gateway); sandboxing optional",
       "background_24x7": null,
       "multi_agent": null,
       "schedules_routines": null,
       "memory": "persistent memory on user's hardware",
       "approvals": "pairing approval for unknown senders; remote action approvals in mobile apps",
       "platforms": "macOS, Windows, Linux, iOS, Android, WhatsApp, Telegram, Slack, Discord, iMessage, Teams, Signal, Google Chat",
       "pricing": "Free, MIT license; no paid tier/hosted service",
       "availability": "global, self-hosted; 391.5k GitHub stars (2026-10-10)",
       "seed": false
      },
      {
       "id": "lindy/lindy",
       "name": "Lindy (AI assistant / AI teammate)",
       "vendor": "Lindy",
       "vendor_key": "lindy",
       "url": "https://wf.lindy.ai/blog/lindy-assistant-launch",
       "launch_date": null,
       "status": null,
       "models": "user-selectable; 'most major models are available'",
       "model_ids": [],
       "own_computer": "Autopilot: agents use their own computers in the cloud",
       "background_24x7": true,
       "multi_agent": null,
       "schedules_routines": true,
       "memory": "memory stored as plain files the user can open and edit",
       "approvals": "Anything with outside impact (send email, update ticket, post, publish) waits for approval; read-only lookups don't",
       "platforms": "iMessage, email, Slack, browser (Chrome extension), web",
       "pricing": "$49.99 per user/month for 5,000 credits; top-up $10 per 1,000 credits; $50 free credits (7 days)",
       "availability": null,
       "seed": false
      },
      {
       "id": "minimax/maxclaw",
       "name": "MaxClaw (MiniMax official cloud OpenClaw) / MiniMax Agent 'Mavis'",
       "vendor": "MiniMax",
       "vendor_key": "minimax",
       "url": "https://agent.minimax.io/activity/max-claw",
       "launch_date": null,
       "status": null,
       "models": "minimax/minimax-m2.7",
       "model_ids": [
        "minimax/m2.7"
       ],
       "own_computer": "officially hosted cloud agent with 50GB cloud workspace; desktop app supports local-to-cloud task handoff",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": "long-term memory, 50GB cloud storage",
       "approvals": null,
       "platforms": null,
       "pricing": "$19/month (English MaxClaw page comparison table)",
       "availability": null,
       "seed": false
      },
      {
       "id": "zhipu/autoclaw",
       "name": "AutoClaw (澳龙) — Zhipu one-click OpenClaw desktop agent with AutoGLM browser use",
       "vendor": "Zhipu AI (Z.ai)",
       "vendor_key": "zhipu",
       "url": "https://autoglm.zhipuai.cn/autoclaw",
       "launch_date": null,
       "status": null,
       "models": "Zhipu GLM series (default; GLM-5.3-Flash advertised), DeepSeek (switchable)",
       "model_ids": [],
       "own_computer": "none — runs on the user's own PC (local desktop app) with browser automation",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": null,
       "platforms": "Windows 10+, macOS, Linux (x86/ARM), Kylin, iOS, Android, Feishu, WeCom, WeChat, Lark",
       "pricing": "free basic tier with daily free credits; paid plans for heavier use; new users get 200M tokens",
       "availability": null,
       "seed": false
      },
      {
       "id": "tencent/workbuddy",
       "name": "WorkBuddy (腾讯龙虾) — Tencent desktop AI agent workbench (QClaw users migrated in)",
       "vendor": "Tencent",
       "vendor_key": "tencent",
       "url": "https://www.codebuddy.cn/work/",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": null,
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": "Windows, macOS, UOS/Kylin, IM (WeCom, QQ, Feishu, DingTalk), mini-program",
       "pricing": null,
       "availability": "China; QClaw (WeChat remote agent) being shut down with data migration to WorkBuddy",
       "seed": false
      },
      {
       "id": "amazon/alexa-plus",
       "name": "Alexa+ (agentic capabilities via Nova Act / 'experts')",
       "vendor": "Amazon",
       "vendor_key": "amazon",
       "url": "https://www.aboutamazon.com/news/devices/new-alexa-generative-artificial-intelligence",
       "launch_date": "2025-02-26",
       "status": null,
       "models": "LLMs on Amazon Bedrock (incl. Amazon Nova); Nova Act for web navigation",
       "model_ids": [],
       "own_computer": "cloud-side web navigation 'behind the scenes' (agentic capability described as forthcoming: 'will enable')",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": "$19.99/month; free with Prime",
       "availability": "All customers US & Canada; early access BR, UK, MX, IT, ES, DE, AT, FR; India launch",
       "seed": false
      },
      {
       "id": "cognition/poke",
       "name": "Poke (The Interaction Company; acquired by Cognition 2026-07-23)",
       "vendor": "Cognition (The Interaction Company of California)",
       "vendor_key": "cognition",
       "url": "https://poke.com/",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": null,
       "background_24x7": true,
       "multi_agent": null,
       "schedules_routines": true,
       "memory": "memory used proactively",
       "approvals": null,
       "platforms": "Apple Messages (iMessage), WhatsApp, Telegram, SMS/text",
       "pricing": "Free $0; Pro $19/month; Ultra $199/month",
       "availability": "global consumer; 'only AI agent approved to text natively on Apple Messages'",
       "seed": false
      },
      {
       "id": "cognition/devin",
       "name": "Devin (autonomous software engineer; Devin Cloud)",
       "vendor": "Cognition",
       "vendor_key": "cognition",
       "url": "https://devin.ai/",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [
        "openai/gpt-6-astra"
       ],
       "own_computer": "every session runs in its own VM; spins up Windows/Mac/Linux VMs and its own browser",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "cursor/cloud-agents",
       "name": "Cursor Cloud Agents (formerly Background Agents)",
       "vendor": "Cursor (Anysphere)",
       "vendor_key": "cursor",
       "url": "https://cursor.com/docs/background-agent",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "isolated cloud VMs with full dev environment; can control desktop and browser",
       "background_24x7": null,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": "API pricing for selected model; paid Cursor plan required",
       "availability": "paid Cursor plans",
       "seed": false
      },
      {
       "id": "zapier/zapier-agents",
       "name": "Zapier Agents",
       "vendor": "Zapier",
       "vendor_key": "zapier",
       "url": "https://zapier.com/agents",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": null,
       "background_24x7": true,
       "multi_agent": null,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "bytedance/doubao-work",
       "name": "Doubao Work (豆包工作) — ByteDance agent work platform (Doubao Agent mode + Feishu)",
       "vendor": "ByteDance",
       "vendor_key": "bytedance",
       "url": "https://www.feishu.cn/content/article/7677519271848610746",
       "launch_date": null,
       "status": null,
       "models": "ByteDance Seed (agent/planning), Seedance (video), Seedream (image)",
       "model_ids": [],
       "own_computer": "cloud-run tasks; can operate browser and parts of the computer UI within authorization",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": true,
       "memory": null,
       "approvals": "user should confirm before deletion, publishing, payment, sending messages, modifying key data",
       "platforms": null,
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "baidu/dumate",
       "name": "DuMate — Baidu general-purpose agent",
       "vendor": "Baidu",
       "vendor_key": "baidu",
       "url": "https://tirto.id/baidu-advances-agent-portfolio-to-embrace-the-agent-era-champions-daily-active-agents-as-key-metric-hv9L",
       "launch_date": "2026-03",
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": "reads screens and operates software (device/cloud split not stated)",
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": null,
       "availability": null,
       "seed": false
      },
      {
       "id": "perplexity/comet-background-assistants",
       "name": "Perplexity Comet Background Assistants (+ Comet Assistant, Email Assistant)",
       "vendor": "Perplexity",
       "vendor_key": "perplexity",
       "url": "https://web.archive.org/web/2025/https://www.perplexity.ai/hub/blog/comet-is-now-available-to-everyone-worldwide",
       "launch_date": null,
       "status": null,
       "models": null,
       "model_ids": [],
       "own_computer": null,
       "background_24x7": true,
       "multi_agent": true,
       "schedules_routines": null,
       "memory": null,
       "approvals": null,
       "platforms": null,
       "pricing": "Background Assistants and Email Assistant for Perplexity Max subscribers (Max price not on captured page)",
       "availability": "Comet free worldwide; Background Assistants for Max",
       "seed": false
      }
     ],
     "benchmarks": [
      {
       "id": "dots_changing_scope_permissions_alignment_pass_rate",
       "name": "OpenAI dots — Adapting to Changing Scope and Permissions (alignment pass rate)",
       "description": "New OpenAI eval in GPT-6 Astra system card Appendix 12.3.5.1: each episode = one task with an external environment change mid-execution (permission revoked / authorization scope changed); pass = agent adapts, e.g. pauses no-longer-authorized actions. 49 episodes incl. 17 explicit permission-change cases. Run by OpenAI on the dots harness. https://web.archive.org/web/2026/https://deploymentsafety.o",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "dots_misleading_proactivity_misalignment_rate_lower_better",
       "name": "OpenAI dots — Robustness to Misleading Proactivity Inputs (misalignment rate)",
       "description": "New OpenAI eval (system card 12.3.5.3): synthetic pipeline generates user tasks, ChatGPT Work environments and notifications with misleading hints that encourage unsupported conclusions or inappropriate actions; 151 tasks. OpenAI, dots with GPT-6 Astra. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "agentic_misaligned_outcome_rate_v2_lower_better",
       "name": "Misaligned outcomes in realistic work environments v2 (OpenAI, harder subset)",
       "description": "Existing DB id. System card 12.3.3 reports the dots-harness run (custom dots confirmation policy) of the harder, subselected realistic-work-environment evals adapted from ChatGPT Work; compared with the Codex harness. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "external_agent_board_instruction_following_rate_lower_better",
       "name": "Unrequested external-agent instruction-following rate (lower better)",
       "description": "Existing DB id. System card 12.3.4 repeats the eval with the dots harness (browsing task, no internet, cached message board). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "dots_cyber_misuse_monitor_block_rate_high_risk",
       "name": "OpenAI cyber misuse-monitor block rate — high-risk cyber activity (dots harness vs Codex baseline)",
       "description": "System card 12.6.2.3: defensive-use eval set spanning general defensive work and activity reserved for Daybreak Blue/Red; GPT-6 Astra run through dots harness and baseline (Codex) harness to compare system-safeguard block rates for high-risk cyber activity. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "dots_cyber_misuse_monitor_block_rate_exploit_dev_redteam",
       "name": "OpenAI cyber misuse-monitor block rate — exploit development and red-teaming (dots harness)",
       "description": "System card 12.6.2.3: same harness comparison; block rate for exploit-development and red-teaming requests (92% in both dots and baseline configurations). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "warning_barrier_persistence_rate_v2_lower_better",
       "name": "OpenAI Respecting Warnings / warning circumvention (Sep-2026 updated version)",
       "description": "Existing DB id. Dots appendix 12.3.1.2 reruns it for GPT-6 Astra across simulated-time budgets (4 min / 30 min / 4 h / 1 yr; model given a deadline, clock tool and wait). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "broken_search_tool_failure_rate_v2_lower_better",
       "name": "OpenAI Broken Search Tool (Sep-2026 updated version) — failure rate",
       "description": "Existing DB id. Dots appendix 12.3.2.2 reruns it for GPT-6 Astra across simulated-time budgets. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log"
      },
      {
       "id": "remote_labor_index",
       "name": "Remote Labor Index (RLI) — Scale Labs leaderboard automation rate",
       "description": "Scale AI + Center for AI Safety. 240 end-to-end freelance projects from 358 Upwork freelancers across 23 domains (230 private set used for leaderboard; 10 public); mean human time 28.9 h, $143,991 total value. Agents run in CLI (OpenHands) or computer-use GUI env, best env reported, $30 budget/task. Metrics: automation rate (primary), Elo (human=1000), dollars earned, cost savings. Board lists age",
       "url": "https://scale.com/leaderboard/rli"
      },
      {
       "id": "agentif_oneday",
       "name": "AgentIF-OneDay (xbench) — overall score",
       "description": "xbench.org, arXiv 2601.20613 (Jan 2026). 104 everyday work/life/study tasks with 767 rubric scoring points, attachments, iterative refinement, latent-instruction inference and open workflows. Gemini-3-Pro-preview as judge. Evaluates commercial general-agent PRODUCTS accessed Dec 2025: ChatGPT-Agent, Genspark, Manus 1.5, MiniMax-Agent (Pro mode).",
       "url": null
      },
      {
       "id": "agentif_oneday_work",
       "name": "AgentIF-OneDay — Work domain score",
       "description": "Work-domain sub-score of AgentIF-OneDay (Table 2).",
       "url": null
      },
      {
       "id": "agentif_oneday_life",
       "name": "AgentIF-OneDay — Life domain score",
       "description": "Life-domain sub-score of AgentIF-OneDay (Table 2).",
       "url": null
      },
      {
       "id": "agentif_oneday_study",
       "name": "AgentIF-OneDay — Study domain score",
       "description": "Study-domain sub-score of AgentIF-OneDay (Table 2).",
       "url": null
      },
      {
       "id": "agentif_oneday_latency_s_lower_better",
       "name": "AgentIF-OneDay — average latency (s, lower better)",
       "description": "Average task latency in AgentIF-OneDay Table 1.",
       "url": null
      },
      {
       "id": "mind2web_2_partial_completion",
       "name": "Mind2Web 2 — partial completion (Agent-as-a-Judge)",
       "description": "OSU NLP (NeurIPS 2025 D&B), arXiv 2506.21506. 130 long-horizon, time-varying agentic-search tasks; task-specific judge agents with tree-structured rubrics check correctness + source attribution. Evaluates PRODUCTS: ChatGPT Search, Perplexity Pro Search, OpenAI Operator, HF Open Deep Research, Claude Research, Grok DeepSearch/DeeperSearch, Perplexity/Gemini/OpenAI Deep Research vs human. Explicit m",
       "url": null
      },
      {
       "id": "mind2web_2_success_rate",
       "name": "Mind2Web 2 — full-task success rate",
       "description": "Mind2Web 2 Table 3 full-task success rate (see mind2web_2_partial_completion).",
       "url": null
      },
      {
       "id": "mind2web_2_pass3",
       "name": "Mind2Web 2 — Pass@3",
       "description": "Mind2Web 2 Table 3 Pass@3.",
       "url": null
      },
      {
       "id": "claw_anything_pass1",
       "name": "Claw-Anything — Pass@1 (always-on personal assistant)",
       "description": "Huawei + PKU et al., arXiv 2605.26086 (25 May 2026). Benchmarks always-on personal assistants (OpenClaw / Hermes Agent / Nanobot style) with access to the user's digital world: persona, CLI Linux + GUI Android devices, 40+ backend services, >3-month activity/event stream with noise, OpenClaw heartbeat-style proactive tasks; rubric+executable verifiers (Claw-Eval style, Claude Sonnet 4.5 judge). Al",
       "url": null
      },
      {
       "id": "claw_anything_pass_pow3",
       "name": "Claw-Anything — Pass^3 (success in all 3 runs)",
       "description": "Claw-Anything Table 2 Pass^3 (see claw_anything_pass1).",
       "url": null
      },
      {
       "id": "spreadsheetbench_v1_oai_agent",
       "name": "SpreadsheetBench (912 Q, soft restriction overall) — OpenAI ChatGPT-agent run",
       "description": "SpreadsheetBench full 912-question set as run by OpenAI for the ChatGPT agent launch (OSX + LibreOffice; Copilot in Excel/GPT-4o rows on Windows + Excel). Separate id because harness/environment differ from spreadsheetbench_v1 model runs.",
       "url": null
      },
      {
       "id": "online_mind2web_oai_screenshot",
       "name": "Online-Mind2Web — OpenAI-reported (screenshot-only, OpenAI judge)",
       "description": "Online-Mind2Web (300 live-web tasks) as reported by OpenAI in the GPT-5.4 launch post; screenshot-based observations, OpenAI's own judge (not published). Not comparable with human-eval online_mind2web_human.",
       "url": null
      },
      {
       "id": "oai_agent_pi_irrelevant_instructions_text",
       "name": "OpenAI agent PI eval — irrelevant instructions, text browser (synthetic) — % correctly disregarded",
       "description": "ChatGPT agent system card Table 12. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_pi_irrelevant_instructions_visual",
       "name": "OpenAI agent PI eval — irrelevant instructions, visual browser — % resisted",
       "description": "Table 12; red-team-derived scenarios on the visual browser tool. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_pi_incontext_exfil_visual",
       "name": "OpenAI agent PI eval — in-context data exfiltration, visual browser — % resisted",
       "description": "Table 12. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_pi_active_exfil_visual",
       "name": "OpenAI agent PI eval — active data exfiltration, visual browser — % resisted",
       "description": "Table 12; agent must actively fetch data to exfiltrate. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_confirmation_recall",
       "name": "OpenAI agent confirmation recall (asks user before relevant actions)",
       "description": "Table 13; underestimate per OpenAI. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_high_stakes_financial_refusal",
       "name": "OpenAI agent refusal — high-stakes financial activities",
       "description": "Table 14 (e.g. account transfers). Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_privacy_invasion_refusal",
       "name": "OpenAI agent refusal — privacy invasion tasks",
       "description": "Table 14. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "oai_agent_disallowed_financial_refusal",
       "name": "OpenAI agent refusal — disallowed financial activities (e.g. gambling)",
       "description": "Table 14. Source: ChatGPT agent System Card (OpenAI, Jul 2025), product-level eval of ChatGPT agent vs Operator (4o and o3 versions); measures model behavior only, not full mitigation stack.",
       "url": null
      },
      {
       "id": "layerx_phishing_block_rate_v1",
       "name": "LayerX AI-browser phishing block rate (100 known phishing sites, Sep 2025)",
       "description": "LayerX Security (now Akamai) independent test, published 2025-09-08: 100 live phishing sites from OpenPhish/PhishTank opened in each browser with default protections. Edge 54%, Chrome 47% (non-AI baselines), Dia 46%, Comet 7%, Genspark browser 7%. Archived copy saved (original blog now redirects to akamai.com).",
       "url": null
      },
      {
       "id": "layerx_phishing_block_rate_atlas_test",
       "name": "LayerX in-the-wild web-attack block rate (103 attacks, Oct 2025)",
       "description": "LayerX Security, published 2025-10-27 with the 'ChatGPT Tainted Memories' Atlas CSRF disclosure: 103 in-the-wild phishing/malicious pages; Atlas stopped 5.8% (97/103 got through); Edge 53%, Chrome 47% as non-AI baselines.",
       "url": null
      },
      {
       "id": "wildclawbench_harness_openclaw",
       "name": "WildClawBench score — OpenClaw harness (harness comparison, Table 3)",
       "description": "InternLM WildClawBench (arXiv 2605.10912, May 2026): 60 hand-built real-world long-horizon tasks in Docker (OpenClaw environment, multimodal, bilingual). Table 3 re-runs 4 models under 4 agent harnesses (OpenClaw, Claude Code, Codex, Hermes Agent) to measure harness effects; this id = OpenClaw harness column. Main board (DB id wildclawbench) uses OpenClaw harness, 19 models, top Claude Opus 4.7 62",
       "url": null
      },
      {
       "id": "wildclawbench_harness_claude_code",
       "name": "WildClawBench score — Claude Code harness (harness comparison, Table 3)",
       "description": "InternLM WildClawBench (arXiv 2605.10912, May 2026): 60 hand-built real-world long-horizon tasks in Docker (OpenClaw environment, multimodal, bilingual). Table 3 re-runs 4 models under 4 agent harnesses (OpenClaw, Claude Code, Codex, Hermes Agent) to measure harness effects; this id = Claude Code harness column. Main board (DB id wildclawbench) uses OpenClaw harness, 19 models, top Claude Opus 4.7",
       "url": null
      },
      {
       "id": "wildclawbench_harness_codex",
       "name": "WildClawBench score — Codex harness (harness comparison, Table 3)",
       "description": "InternLM WildClawBench (arXiv 2605.10912, May 2026): 60 hand-built real-world long-horizon tasks in Docker (OpenClaw environment, multimodal, bilingual). Table 3 re-runs 4 models under 4 agent harnesses (OpenClaw, Claude Code, Codex, Hermes Agent) to measure harness effects; this id = Codex harness column. Main board (DB id wildclawbench) uses OpenClaw harness, 19 models, top Claude Opus 4.7 62.2%",
       "url": null
      },
      {
       "id": "wildclawbench_harness_hermes_agent",
       "name": "WildClawBench score — Hermes Agent harness (harness comparison, Table 3)",
       "description": "InternLM WildClawBench (arXiv 2605.10912, May 2026): 60 hand-built real-world long-horizon tasks in Docker (OpenClaw environment, multimodal, bilingual). Table 3 re-runs 4 models under 4 agent harnesses (OpenClaw, Claude Code, Codex, Hermes Agent) to measure harness effects; this id = Hermes Agent harness column. Main board (DB id wildclawbench) uses OpenClaw harness, 19 models, top Claude Opus 4.",
       "url": null
      },
      {
       "id": "dots_chained_tasks_moderate_scope_violation_rate_5_intervening_tasks_lower_better",
       "name": "OpenAI dots — Maintaining Boundaries Across Chained Tasks (moderate scope-violation flag rate) — 5 intervening tasks",
       "description": "New OpenAI eval (system card 12.3.5.2): initial task + 5 or 10 related intervening tasks + final task in one persistent environment; authorization scope changes between tasks without being stated. Reports flag rate of moderate-severity scope violations (no severe breach/exfiltration observed). OpenAI, dots harness, GPT-6 Astra. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/g",
       "url": null
      },
      {
       "id": "dots_chained_tasks_moderate_scope_violation_rate_10_intervening_tasks_lower_better",
       "name": "OpenAI dots — Maintaining Boundaries Across Chained Tasks (moderate scope-violation flag rate) — 10 intervening tasks",
       "description": "New OpenAI eval (system card 12.3.5.2): initial task + 5 or 10 related intervening tasks + final task in one persistent environment; authorization scope changes between tasks without being stated. Reports flag rate of moderate-severity scope violations (no severe breach/exfiltration observed). OpenAI, dots harness, GPT-6 Astra. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/g",
       "url": null
      },
      {
       "id": "warning_barrier_persistence_rate_v2_simulated_time_budget_4_minutes_dots_app_lower_better",
       "name": "OpenAI Respecting Warnings / warning circumvention (Sep-2026 updated version) — simulated-time budget 4 minutes (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.1.2 reruns it for GPT-6 Astra across simulated-time budgets (4 min / 30 min / 4 h / 1 yr; model given a deadline, clock tool and wait). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 4 minutes (dots appendix).",
       "url": null
      },
      {
       "id": "warning_barrier_persistence_rate_v2_simulated_time_budget_30_minutes_and_4_h_lower_better",
       "name": "OpenAI Respecting Warnings / warning circumvention (Sep-2026 updated version) — simulated-time budget 30 minutes and 4 hours (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.1.2 reruns it for GPT-6 Astra across simulated-time budgets (4 min / 30 min / 4 h / 1 yr; model given a deadline, clock tool and wait). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 30 minutes and 4 hours (dots appendix).",
       "url": null
      },
      {
       "id": "warning_barrier_persistence_rate_v2_simulated_time_budget_1_year_dots_append_lower_better",
       "name": "OpenAI Respecting Warnings / warning circumvention (Sep-2026 updated version) — simulated-time budget 1 year (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.1.2 reruns it for GPT-6 Astra across simulated-time budgets (4 min / 30 min / 4 h / 1 yr; model given a deadline, clock tool and wait). https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 1 year (dots appendix).",
       "url": null
      },
      {
       "id": "broken_search_tool_failure_rate_v2_simulated_time_budget_4_minutes_dots_app_lower_better",
       "name": "OpenAI Broken Search Tool (Sep-2026 updated version) — failure rate — simulated-time budget 4 minutes (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.2.2 reruns it for GPT-6 Astra across simulated-time budgets. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 4 minutes (dots appendix).",
       "url": null
      },
      {
       "id": "broken_search_tool_failure_rate_v2_simulated_time_budget_30_minutes_and_4_h_lower_better",
       "name": "OpenAI Broken Search Tool (Sep-2026 updated version) — failure rate — simulated-time budget 30 minutes and 4 hours (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.2.2 reruns it for GPT-6 Astra across simulated-time budgets. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 30 minutes and 4 hours (dots appendix).",
       "url": null
      },
      {
       "id": "broken_search_tool_failure_rate_v2_simulated_time_budget_1_year_dots_append_lower_better",
       "name": "OpenAI Broken Search Tool (Sep-2026 updated version) — failure rate — simulated-time budget 1 year (dots appendix)",
       "description": "Existing DB id. Dots appendix 12.3.2.2 reruns it for GPT-6 Astra across simulated-time budgets. https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log Setting: simulated-time budget 1 year (dots appendix).",
       "url": null
      },
      {
       "id": "anthropic_claude_for_chrome_pi_asr_no_safety_mitigations_lower_better",
       "name": "Anthropic Claude for Chrome adversarial prompt-injection ASR (123 cases / 29 scenarios, lower better) — no safety mitigations",
       "description": "Anthropic first-party red-team of the Claude for Chrome browser-agent PRODUCT (research preview, Aug 2025): 123 test cases across 29 attack scenarios, autonomous mode, with vs without product safety mitigations. Setting: no safety mitigations.",
       "url": null
      },
      {
       "id": "anthropic_claude_for_chrome_pi_asr_autonomous_mode_with_safety_mitigations_lower_better",
       "name": "Anthropic Claude for Chrome adversarial prompt-injection ASR (123 cases / 29 scenarios, lower better) — autonomous mode with safety mitigations",
       "description": "Anthropic first-party red-team of the Claude for Chrome browser-agent PRODUCT (research preview, Aug 2025): 123 test cases across 29 attack scenarios, autonomous mode, with vs without product safety mitigations. Setting: autonomous mode with safety mitigations.",
       "url": null
      },
      {
       "id": "anthropic_claude_for_chrome_browser_specific_pi_asr_before_browser_specific_mitigations_lower_better",
       "name": "Anthropic Claude for Chrome — browser-specific prompt-injection challenge set ASR (4 attack types, lower better) — before browser-specific mitigations",
       "description": "Challenge set of four browser-specific attack types (hidden DOM form fields, URL text, tab-title injections) for Claude for Chrome, before vs after new mitigations. Setting: before browser-specific mitigations.",
       "url": null
      },
      {
       "id": "anthropic_claude_for_chrome_browser_specific_pi_asr_with_browser_specific_mitigations_lower_better",
       "name": "Anthropic Claude for Chrome — browser-specific prompt-injection challenge set ASR (4 attack types, lower better) — with browser-specific mitigations",
       "description": "Challenge set of four browser-specific attack types (hidden DOM form fields, URL text, tab-title injections) for Claude for Chrome, before vs after new mitigations. Setting: with browser-specific mitigations.",
       "url": null
      }
     ],
     "sources": [
      {
       "url": "https://web.archive.org/web/2026/https://x.ai/news/grok-bot-more-plans",
       "title": "Grok Bot — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://research.meta.ai/blog/how-we-built-safety-into-muse (via security.muse.ai)",
       "title": "Muse — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://web.archive.org/web/2026/https://openai.com/index/introducing-dots/",
       "title": "ChatGPT dots — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://blog.google/innovation-and-ai/products/gemini-app/next-evolution-gemini-app/",
       "title": "Gemini Spark — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://cloud.google.com/blog/products/ai-machine-learning/welcome-to-gemini-at-work-2026",
       "title": "Gemini agent (Gemini Enterprise / Gemini at Work 2026) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://support.claude.com/en/articles/12138966-release-notes",
       "title": "Claude Cowork (now merged into Claude) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.microsoft.com/en-us/copilot/blog/2026/06/02/introducing-microsoft-scout-your-always-on-personal-agent/",
       "title": "Microsoft Autopilot (previously Microsoft Scout) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.microsoft.com/en-us/copilot/blog/2026/03/09/copilot-cowork-a-new-way-of-getting-work-done/",
       "title": "Microsoft 365 Copilot Cowork — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://support.microsoft.com/en-us/microsoft-copilot/using-copilot-tasks",
       "title": "Microsoft Copilot Tasks (consumer; migrating to Copilot Cowork) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.kimi.com/en-cn/help/agent/agent-overview",
       "title": "Kimi Claw — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://manus.im/blog",
       "title": "Manus 2.0 (Cascade harness, Cloud Computer, Automations, Manus Studio) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://manus.im/blog/introducing-manus-2-0",
       "title": "Cue (Manus personal-agents app) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://web.archive.org/web/2026/https://www.perplexity.ai/hub/blog/introducing-perplexity-computer",
       "title": "Perplexity Computer — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.notion.com/releases/2026-02-24",
       "title": "Notion Custom Agents — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://press.opera.com/?p=3715",
       "title": "Opera Neon (agentic browser: Neon Do + agents) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://mainfunc.ai/blog",
       "title": "Genspark Claw ('AI employee') + Genspark Cloud Computer — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://github.com/openclaw/openclaw",
       "title": "OpenClaw (formerly Clawdbot / Moltbot) — self-hosted personal agent — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://wf.lindy.ai/blog/lindy-assistant-launch",
       "title": "Lindy (AI assistant / AI teammate) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://agent.minimax.io/activity/max-claw",
       "title": "MaxClaw (MiniMax official cloud OpenClaw) / MiniMax Agent 'Mavis' — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://autoglm.zhipuai.cn/autoclaw",
       "title": "AutoClaw (澳龙) — Zhipu one-click OpenClaw desktop agent with AutoGLM browser use — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.codebuddy.cn/work/",
       "title": "WorkBuddy (腾讯龙虾) — Tencent desktop AI agent workbench (QClaw users migrated in) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.aboutamazon.com/news/devices/new-alexa-generative-artificial-intelligence",
       "title": "Alexa+ (agentic capabilities via Nova Act / 'experts') — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://poke.com/",
       "title": "Poke (The Interaction Company; acquired by Cognition 2026-07-23) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://devin.ai/",
       "title": "Devin (autonomous software engineer; Devin Cloud) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://cursor.com/docs/background-agent",
       "title": "Cursor Cloud Agents (formerly Background Agents) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://zapier.com/agents",
       "title": "Zapier Agents — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.feishu.cn/content/article/7677519271848610746",
       "title": "Doubao Work (豆包工作) — ByteDance agent work platform (Doubao Agent mode + Feishu) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://tirto.id/baidu-advances-agent-portfolio-to-embrace-the-agent-era-champions-daily-active-agents-as-key-metric-hv9L",
       "title": "DuMate — Baidu general-purpose agent — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://web.archive.org/web/2025/https://www.perplexity.ai/hub/blog/comet-is-now-available-to-everyone-worldwide",
       "title": "Perplexity Comet Background Assistants (+ Comet Assistant, Email Assistant) — 공식 페이지",
       "what": ""
      },
      {
       "url": "https://www.orcarouter.ai/ko/blog/grok-bot-launch",
       "title": null,
       "what": "Secondary (raw/s04): Grok Bot timeline — beta 2026-08-11, tier expansion 08-21/08-26, Android 09-02, Enterprise 09-03, Team Bots 09-28, Primary Bot ~09-30/10-01, native X access 10-07, @mail.grokbot.c"
      },
      {
       "url": "https://x.com/elonmusk (2026-10-07 post, not fetchable)",
       "title": null,
       "what": "Claimed Grok Bot backend routing to Claude Opus 5.5 etc. — unverified, X posts not fetchable"
      },
      {
       "url": "https://web.archive.org/web/2026/https://x.ai/news/designing-grok-bot",
       "title": null,
       "what": "SpaceXAI design essay (2026-09-03) on persistent agents, roster, shared computer — saved as pages/xai_designing-grok-bot.txt"
      },
      {
       "url": "https://web.archive.org/web/2026/https://x.ai/news/grok-bot-procurement",
       "title": null,
       "what": "Haggle Bot case study: >$100,000 direct savings ($14,220 + $85,662/yr SaaS) — vendor KPI, not benchmark"
      },
      {
       "url": "https://research.meta.ai/blog/introducing-muse-spark-1-3",
       "title": null,
       "what": "Muse Spark 1.3 (2026-09-02) model post; ~20% fewer tool calls, ~25% fewer tokens vs 1.2; benchmark numbers are in a linked report/charts, not in text — model-level, out of scope here"
      },
      {
       "url": "http://security.muse.ai",
       "title": null,
       "what": "How We Built Safety Into Muse (2026-09-08): Hatch daemon in systemd-nspawn cell, Sentinel egress L4/L7, prompt-injection evals ('Muse Spark 1.3 is close to SOTA', no number), bug bounty"
      },
      {
       "url": "https://www.layer3labs.io/guides/meta-muse-pricing",
       "title": null,
       "what": "Secondary: Muse plans Free / Power $20/mo (500M Muse tokens/wk) / Max $100/mo (3B/wk) per Meta help center (not fetched — 400/auth)"
      },
      {
       "url": "https://axios.com/2026/09/08/meta-debuts-muse-personal-ai-agent",
       "title": null,
       "what": "News: Muse launch 2026-09-08, 18+, US only, free + $20 + $100 tiers"
      },
      {
       "url": "https://web.archive.org/web/2026/https://deploymentsafety.openai.com/gpt-6-astra/change-log",
       "title": null,
       "what": "GPT-6 Astra System Card Appendix 12 'Dots' (added 2026-09-29): bulk prompt-injection red-team 100 rollouts / 50,000 emails incl. 16,600 attacks -> no scored successes; iterative attack 100 chains / 2,"
      },
      {
       "url": "https://help.openai.com/articles/20001529",
       "title": null,
       "what": "dots eligible markets help article (not archived)"
      },
      {
       "url": "https://www.bernama.com/en/world/news.php?id=2613531",
       "title": null,
       "what": "News: dots launched at DevDay; mentions a US$500/mo ChatGPT plan alongside (unverified)"
      },
      {
       "url": "https://www.digitaltrends.com/computing/gemini-spark-is-no-longer-restricted-to-googles-priciest-ultra-tier/",
       "title": null,
       "what": "News: Spark opened to US AI Pro; not on AI Plus ($7.99) or free"
      },
      {
       "url": "https://cloud.google.com/blog/products/ai-machine-learning/flexible-billing-and-cost-controls-for-agents-on-google-cloud",
       "title": null,
       "what": "Linked from Gemini at Work post: flexible spending options for agents (not fetched)"
      },
      {
       "url": "https://cloud.google.com/gemini-enterprise",
       "title": null,
       "what": "Gemini Enterprise app editions page (archived 2026-10-05, pre-Gemini-agent): Business $21, Standard/Plus $30, PAYG $0 seat fee"
      },
      {
       "url": "https://www.ithome.com/0/927/230.htm",
       "title": null,
       "what": "IT之家 2026-03-09: Tencent WorkBuddy launch (quotes Tencent Cloud WeChat account); models Hunyuan/DeepSeek/GLM/Kimi/MiniMax; 2,000+ internal users"
      },
      {
       "url": "https://www.testingcatalog.com/minimax-launches-managed-always-on-maxclaw-ai-agent.md",
       "title": null,
       "what": "MaxClaw launch coverage (Feb 2026)"
      },
      {
       "url": "https://www.ai-market-watch.com/news/zhipu-launches-autoclaw-a-one-click-local-ai-agent-for-windows-and-macos-yd28k8",
       "title": null,
       "what": "AutoClaw launch ~2026-03-10 (secondary)"
      },
      {
       "url": "https://en.wikipedia.org/wiki/OpenClaw",
       "title": null,
       "what": "OpenClaw history: Clawdbot (Nov 2025) -> Moltbot (2026-01-27) -> OpenClaw (2026-01-30)"
      },
      {
       "url": "https://www.neowin.net/news/microsoft-introduces-copilot-tasks-a-new-way-to-get-things-done-using-ai",
       "title": null,
       "what": "Copilot Tasks research preview announced 2026-02-26 (primary blog URL now redirects)"
      },
      {
       "url": "https://www.techcrunch.com/2025/10/02/perplexitys-comet-ai-browser-now-free-max-users-get-new-background-assistant/",
       "title": null,
       "what": "Perplexity Comet background assistant (Max) Oct 2025"
      },
      {
       "url": "https://pulse2.com/anthropic-merges-claude-cowork-and-chat-into-one-claude-launches-claude-docs-and-claude-slides/",
       "title": null,
       "what": "Claude Cowork merged into Claude 2026-09-16"
      },
      {
       "url": "https://www.stdaily.com/web/gdxw/2026-08/21/content_567862.html",
       "title": null,
       "what": "Doubao 'work task' upgrade Aug 2026: phone remote-controls PC, local + cloud-computer dual modes (news)"
      },
      {
       "url": "https://www.caixinglobal.com/2026-03-18/alibaba-joins-openclaw-driven-ai-agent-race-with-wukong-platform-102424061.html",
       "title": null,
       "what": "Alibaba Wukong enterprise agent platform (2026-03-17, invite-only beta, DingTalk) — not confirmed from a primary page"
      },
      {
       "url": "https://www.ithome.com/0/913/546.htm",
       "title": null,
       "what": "Qwen App task assistant (千问任务助理) invite test from 2026-01-15 — no background/own-computer claim found"
      },
      {
       "url": "https://www.koreaherald.com/article/10700639",
       "title": null,
       "what": "Naver Agent N / shopping agent timeline; Kakao 'Kanana in KakaoTalk' — no always-on cloud agent confirmed"
      },
      {
       "url": "https://arxiv.org/abs/2510.26787",
       "title": null,
       "what": "RLI paper (Scale AI + CAIS, Oct 2025): Table 1 Manus 2.5%, Grok 4 2.1%, Sonnet 4.5 2.1%, GPT-5 1.7%, ChatGPT agent 1.3%, Gemini 2.5 Pro 0.8% (saved work/r_bench/pages/rli_paper.txt lines ~542-547)"
      },
      {
       "url": "https://leaderboard.steel.dev/leaderboards/online-mind2web",
       "title": null,
       "what": "Steel.dev aggregator of Online-Mind2Web (updated 2026-06-29): Browser Use Cloud 97% (custom judge), GPT-5.4 native CU 93%, ChatGPT Atlas Agent Mode 71% (OpenAI-reported in GPT-5.4 post), Gemini 2.5 CU"
      },
      {
       "url": "https://hal.cs.princeton.edu/online_mind2web",
       "title": null,
       "what": "HAL (Princeton) Online-Mind2Web leaderboard: Browser-Use / SeeAct scaffolds × base models, top ~42% (saved om2w_hal.txt)"
      },
      {
       "url": "https://arxiv.org/abs/2605.14678",
       "title": null,
       "what": "π-Bench (proactive personal-assistant agents, OpenClaw-style, Nanobot scaffold; 100 tasks, 5 user profiles) — model-level PROC/COMP; already in DB as pi_bench_proc/pi_bench_comp (saved pi_bench.txt)"
      },
      {
       "url": "https://arxiv.org/abs/2606.05342",
       "title": null,
       "what": "SentinelBench (Microsoft Research, long-running monitoring agents) — already in DB as sentinelbench (saved sentinelbench.txt)"
      },
      {
       "url": "https://layerxsecurity.com/blog/cometjacking-how-one-click-can-turn-perplexitys-comet-ai-browser-against-you",
       "title": null,
       "what": "LayerX 'CometJacking' one-click prompt-injection exfiltration disclosure for Comet (qualitative, no rate)"
      },
      {
       "url": "https://os-world.github.io/",
       "title": null,
       "what": "OSWorld-Verified official results xlsx (static/data/osworld_verified_results.xlsx, 1,077 rows, saved as pages/osworld_verified_results_Eval_Results.txt): commercial desktop-agent frameworks e.g. Intel"
      },
      {
       "url": "https://aiagentindex.mit.edu/",
       "title": null,
       "what": "MIT 2025 AI Agent Index: documents origins, capabilities and safety features of 30 prominent deployed agents (landing page names ChatGPT Agent, Atlas, Comet, Manus, Claude, Copilot); per-agent pages ("
      },
      {
       "url": "https://deploymentsafety.openai.com/gpt-6-astra",
       "title": null,
       "what": "GPT-6 Astra System Card Appendix 12 'Dots' (added 2026-09-29): product-level dots evals (prompt-injection GPT-Red bulk 100 rollouts/16,600 attack emails and iterative 2,638 attempts with no scored suc"
      },
      {
       "url": "https://arxiv.org/abs/2605.27922",
       "title": null,
       "what": "Harness-Bench (May 2026): 106 sandboxed tasks, 5,194 trajectories, factorial model x harness design (OpenClaw, Hermes, Codex etc.); per-harness numbers only in figures — not extracted (saved harnessbe"
      },
      {
       "url": "https://github.com/internlm/WildClawBench",
       "title": null,
       "what": "WildClawBench repo + leaderboard (OpenClaw harness; per-harness board)"
      },
      {
       "url": "https://research.perplexity.ai/articles/wandr-benchmark-evaluating-research-agents-that-must-search-wide-and-deep",
       "title": null,
       "what": "Perplexity WANDR (500 wide-and-deep research tasks, 6 production systems): Perplexity Search as Code 0.363 soft F1 / 0.133 hard F1, 'Anthropic' 0.249/0.072, others <=0.121; xhigh 45-task subset 0.447."
      },
      {
       "url": "https://arxiv.org/abs/2602.11685",
       "title": null,
       "what": "DRACO (Perplexity, Feb 2026) deep-research product benchmark: Perplexity Deep Research (Opus 4.6) 70.5, Gemini Deep Research 59.0, OpenAI Deep Research o3 52.1 — already in DB (draco*, saved draco.txt"
      },
      {
       "url": "https://www.computerworld.com/article/4152323/microsoft-adds-multi-model-ai-to-copilot-researcher-raising-accuracy-stakes.html",
       "title": null,
       "what": "Microsoft 365 Copilot Researcher 'Critique' (GPT drafts + Claude review) claims +7.0 pts aggregated DRACO score, +13.88% over Perplexity DR (Opus 4.6); secondary reports of 57.4 absolute conflict — no"
      },
      {
       "url": "https://www.aiagentslibrary.com/ai-agent-test-lab/",
       "title": null,
       "what": "'AI Agent Test Lab' (independent blog, 2026): 10 business tasks per agent, rates Claude Cowork 9.3/10, ChatGPT Work 9.15, OpenAI Dots 8.8, Gemini Spark 8.7 — informal, pointer only (numbers from searc"
      },
      {
       "url": "https://www.xugj520.cn/en/archives/ai-agents-comparison.html",
       "title": null,
       "what": "Informal July 2025 shoot-out of Genspark / Manus / OpenAI agent / Comet on 9 tasks (one run each) — anecdotal"
      },
      {
       "url": "https://arena.ai/blog/agent-arena-2024/",
       "title": null,
       "what": "arena.ai Agent Arena (Agent Mode, launched 2026-06-04; Aug 17 2026 update adds cost/Pareto) ranks base models on real-user agent tasks — model-level, DB id arena_agent_net_improvement"
      },
      {
       "url": "https://www.anthropic.com/system-cards",
       "title": null,
       "what": "Anthropic system cards report Claude Cowork / Claude in Chrome browser-use prompt-injection ASR (DB ids browser_use_cowork_asr_auto_mode / _no_safeguards) — product-level evals already in DB"
      },
      {
       "url": "https://labs.scale.com/leaderboard/rli",
       "title": null,
       "what": "Scale Labs RLI board also exposes Elo / dollars-earned / cost-savings metrics (not in RSC rows; only automation-rate score extracted)"
      },
      {
       "url": "https://andonlabs.com/evals/vending-bench-arena",
       "title": null,
       "what": "Andon Labs Vending-Bench 2 / Arena (long-horizon business-running, multi-agent competitive): latest boards list base models only (GPT-6, Opus 5.5, Gemini 4 Argon, Grok 4.7 ...) — no agent products (sa"
      },
      {
       "url": "https://the-agent-company.com/",
       "title": null,
       "what": "TheAgentCompany (175 simulated-company tasks, OpenHands/OWL scaffolds) — model-level board (page JS-only, not saved)"
      }
     ]
    },
    // GENERATED:BOTS_DATA:END
    ENGINE_BENCH: [['aa_intelligence_index_v4_3', 'AA 지능 지수'], ['gdpval_aa_v2_1', 'GDPval-AA v2.1'], ['terminal_bench_4_0_aa', 'Terminal-Bench 4.0'],
                   ['automationbench_aa', 'AutomationBench'], ['aa_briefcase_v1_1', 'Briefcase Elo']],

    _el: function(tag, cls, text) { var e = document.createElement(tag); if (cls) e.className = cls; if (text != null) e.textContent = text; return e; },
    _esc: function(s) { return String(s == null ? '' : s).replace(/[&<>"']/g, function(c) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]; }); },
    _idx: function() { return (window.App && App.getScoreIndex) ? App.getScoreIndex() : null; },
    _val: function(mid, bid) { var i = this._idx(); var s = i && i.byModelBench[mid + '|' + bid]; return s ? s.value : null; },
    _bench: function(bid) { var i = this._idx(); return (i && i.byBench[bid]) || []; },
    _name: function(mid) { var m = this._models[mid]; if (m && m.name && m.name !== mid) return m.name; var p = this._prod[mid]; return p ? p.name : mid.split('/').pop(); },
    _chart: function(el, opt) { var c = echarts.init(el); c.setOption(opt); this._charts.push(c); return c; },
    _link: function(url, text) { var a = this._el('a', 'text-xs text-blue-400 hover:underline', text || '원문 ↗'); a.href = url; a.target = '_blank'; a.rel = 'noopener'; return a; },
    _section: function(root, title, blurb) {
        var s = this._el('div', 'mb-10'); s.appendChild(this._el('h2', 'text-section mb-2', title));
        if (blurb) s.appendChild(this._el('p', 'text-sm text-gray-400 mb-4', blurb));
        root.appendChild(s); return s;
    },
    _vendorColor: function(v) {
        var map = { xai: Theme.series[3], spacexai: Theme.series[3], openai: Theme.series[0], google: Theme.series[1], meta: Theme.series[4], anthropic: Theme.series[2], microsoft: Theme.series[5] };
        return map[String(v || '').toLowerCase()] || Theme.textMuted;
    },
    _cellColor: function(v, min, max, lower) {
        if (v == null || max === min) return Theme.textMuted;
        var t = (v - min) / (max - min); if (lower) t = 1 - t;
        var st = [[239, 68, 68], [245, 158, 11], [16, 185, 129]], a = t < 0.5 ? st[0] : st[1], b = t < 0.5 ? st[1] : st[2], u = t < 0.5 ? t * 2 : (t - 0.5) * 2;
        return 'rgb(' + [0, 1, 2].map(function(k) { return Math.round(a[k] + (b[k] - a[k]) * u); }).join(',') + ')';
    },

    render: function() {
        if (this._initialized) return;
        if (!window.App || !App.data || !App.data.scores || !App.data.scores.length || !this._idx()) return;
        var self = this, root = document.getElementById('bots-content');
        if (!root) return;
        root.textContent = '';
        this._models = {}; (App.data.models || []).forEach(function(m) { self._models[m.id] = m; });
        this._prod = {}; this.BOTS_DATA.products.forEach(function(p) { self._prod[p.id] = p; });
        this._renderGuide(root);
        this._renderTimeline(root);
        this._renderMatrix(root);
        this._renderEngines(root);
        this._renderResults(root);
        this._renderBenchCatalogue(root);
        this._renderSources(root);
        window.addEventListener('resize', function() { self._charts.forEach(function(c) { c.resize(); }); });
        this._initialized = true;
    },

    _renderGuide: function(root) {
        var self = this, g = this._el('div', 'grid grid-cols-1 lg:grid-cols-3 gap-4 mb-8');
        [['봇(Bot)이란', ['AI에게 자기 컴퓨터(클라우드 VM·브라우저)를 주고, 사용자의 앱에 로그인해 일을 처음부터 끝까지 맡기는 제품입니다.',
                         '노트북을 닫아도 24시간 백그라운드에서 일하고, 끝나면 결과물이나 승인 요청을 들고 돌아옵니다.',
                         '2026년 8~10월 xAI Grok Bot, Meta Muse, ChatGPT dots, Gemini Spark가 잇달아 나오며 하나의 제품 범주가 됐습니다.']],
         ['챗봇·에이전트 모드와 다른 점', ['챗봇은 질문을 기다립니다. 봇은 일정과 루틴에 따라 먼저 움직이고, 여러 봇이 병렬로 협업합니다.',
                                       '작업 방식을 기억하고 한 번 보여 준 워크플로를 루틴으로 저장해 다음부터 스스로 실행합니다.',
                                       '송금·이메일 발송·결제처럼 민감한 작업은 승인을 받고, 비밀번호는 봇이 읽을 수 없는 별도 보관소에 둡니다.']],
         ['비교할 때 볼 것', ['어떤 모델이 엔진인지(자사 모델만 쓰는지, 여러 회사 모델로 라우팅하는지).',
                              '자기 컴퓨터가 있는지, 봇끼리 컴퓨터를 공유하는지, 어디에서 대화하는지(데스크톱·모바일·WhatsApp·Slack).',
                              '가격(구독에 포함 + 사용량 과금)과 승인·감사 기록 같은 안전장치. 봇 제품 자체의 벤치마크는 아직 드뭅니다.']]
        ].forEach(function(c) {
            var d = self._el('div', 'rounded-lg border border-gray-800 p-4 space-y-2');
            d.appendChild(self._el('h3', 'text-sm font-semibold text-gray-200', c[0]));
            c[1].forEach(function(p) { d.appendChild(self._el('p', 'text-sm text-gray-400 leading-relaxed', p)); });
            g.appendChild(d);
        });
        root.appendChild(g);
    },

    _renderTimeline: function(root) {
        var self = this;
        var P = this.BOTS_DATA.products.filter(function(p) { return p.launch_date; }).slice().sort(function(a, b) { return a.launch_date.localeCompare(b.launch_date); });
        if (!P.length) return;
        var s = this._section(root, '출시 타임라인 (' + P.length + '개)', '발표일 기준. 같은 회사의 후속 단계(베타 확대, 팀 기능, 모바일)는 각 제품 행의 메모에 있습니다.');
        var c = this._el('div'); c.style.height = Math.max(260, 28 * P.length + 80) + 'px'; s.appendChild(c);
        var t0 = Date.parse(P[0].launch_date);
        this._chart(c, {
            backgroundColor: 'transparent',
            tooltip: { formatter: function(p) { var d = P[p.dataIndex]; return self._esc(d.name) + '<br>' + self._esc(d.vendor) + ' · ' + self._esc(d.launch_date) + (d.status ? ' · ' + self._esc(d.status) : ''); } },
            grid: { left: 8, right: 40, top: 20, bottom: 30, containLabel: true },
            xAxis: { type: 'time', axisLabel: { color: Theme.textMuted }, splitLine: { lineStyle: { color: Theme.border } } },
            yAxis: { type: 'category', inverse: true, data: P.map(function(p) { return p.name; }), axisLabel: { color: Theme.textMuted, fontSize: 10 } },
            series: [{ type: 'scatter', symbolSize: 12, data: P.map(function(p, i) { return { value: [p.launch_date, i], itemStyle: { color: self._vendorColor(p.vendor_key) } }; }),
                       label: { show: true, position: 'right', color: Theme.textDim, fontSize: 9, formatter: function(p) { return P[p.dataIndex].launch_date; } } }]
        });
    },

    _renderMatrix: function(root) {
        var self = this, P = this.BOTS_DATA.products;
        if (!P.length) return;
        var s = this._section(root, '기능 비교표', '각 칸은 공식 페이지에 적힌 내용입니다. 제품명을 누르면 근거 출처가 열립니다. "—"는 원문에서 확인하지 못한 항목입니다.');
        var cols = [['vendor', '회사'], ['launch_date', '출시'], ['status', '상태'], ['models', '엔진 모델'], ['own_computer', '자기 컴퓨터'], ['background_24x7', '24/7'],
                    ['multi_agent', '여러 봇'], ['schedules_routines', '일정·루틴'], ['memory', '기억'], ['approvals', '승인·안전'], ['platforms', '사용 위치'], ['pricing', '가격']];
        var w = this._el('div', 'overflow-x-auto'), t = this._el('table', 'sota-table text-xs'), th = this._el('thead'), hr = this._el('tr');
        hr.appendChild(this._el('th', null, '제품'));
        cols.forEach(function(c) { hr.appendChild(self._el('th', null, c[1])); });
        th.appendChild(hr); t.appendChild(th);
        var tb = this._el('tbody');
        P.forEach(function(p) {
            var tr = self._el('tr');
            var tn = self._el('td', 'font-semibold', p.name); tn.style.whiteSpace = 'nowrap'; tn.style.color = self._vendorColor(p.vendor_key);
            if (p.url) { tn.style.cursor = 'pointer'; tn.title = p.url; tn.addEventListener('click', function() { window.open(p.url, '_blank', 'noopener'); }); }
            tr.appendChild(tn);
            cols.forEach(function(c) {
                var v = p[c[0]];
                if (Array.isArray(v)) v = v.join(', ');
                if (v === true) v = '예'; else if (v === false) v = '아니오';
                var td = self._el('td', null, v == null || v === '' ? '—' : String(v));
                td.style.maxWidth = '260px'; td.style.verticalAlign = 'top';
                if (v == null || v === '') td.style.color = Theme.textDisabled;
                tr.appendChild(td);
            });
            tb.appendChild(tr);
        });
        t.appendChild(tb); w.appendChild(t); s.appendChild(w);
    },

    _renderEngines: function(root) {
        var self = this, ids = {};
        this.BOTS_DATA.products.forEach(function(p) { (p.model_ids || []).forEach(function(m) { if (self._models[m]) ids[m] = (ids[m] || []).concat([p.name]); }); });
        var mids = Object.keys(ids); if (!mids.length) return;
        var s = this._section(root, '봇 뒤의 엔진 모델', '각 봇이 공식적으로 밝힌 엔진 모델의 독립 평가 점수입니다(Artificial Analysis). 봇의 성능은 모델 외에 컴퓨터 환경·도구·기억 설계에도 좌우됩니다.');
        var w = this._el('div', 'overflow-x-auto'), t = this._el('table', 'sota-table text-xs'), th = this._el('thead'), hr = this._el('tr');
        ['모델', '사용하는 봇'].concat(this.ENGINE_BENCH.map(function(b) { return b[1]; })).forEach(function(h) { hr.appendChild(self._el('th', null, h)); });
        th.appendChild(hr); t.appendChild(th);
        var st = {};
        this.ENGINE_BENCH.forEach(function(b) { var vs = mids.map(function(m) { return self._val(m, b[0]); }).filter(function(v) { return v != null; }); st[b[0]] = { min: Math.min.apply(null, vs), max: Math.max.apply(null, vs) }; });
        var tb = this._el('tbody');
        mids.sort(function(a, b) { return (self._val(b, 'aa_intelligence_index_v4_3') || 0) - (self._val(a, 'aa_intelligence_index_v4_3') || 0); });
        mids.forEach(function(m) {
            var tr = self._el('tr'), tn = self._el('td', null, self._name(m)); tn.style.whiteSpace = 'nowrap'; tn.style.cursor = 'pointer';
            tn.addEventListener('click', function() { if (typeof Modal !== 'undefined' && Modal.showModel) Modal.showModel(m); });
            tr.appendChild(tn); tr.appendChild(self._el('td', null, ids[m].join(', ')));
            self.ENGINE_BENCH.forEach(function(b) {
                var v = self._val(m, b[0]), td = self._el('td', null, v == null ? '—' : (Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(1)));
                td.style.textAlign = 'center'; td.style.color = v == null ? Theme.textDisabled : self._cellColor(v, st[b[0]].min, st[b[0]].max, false);
                if (v != null) { td.style.cursor = 'pointer'; td.addEventListener('click', function() { if (typeof Modal !== 'undefined' && Modal.showScoreSource) Modal.showScoreSource(m, b[0]); }); }
                tr.appendChild(td);
            });
            tb.appendChild(tr);
        });
        t.appendChild(tb); w.appendChild(t); s.appendChild(w);
    },

    RESULT_GROUPS: [
        { title: 'Remote Labor Index (Scale) — 실제 프리랜서 프로젝트 자동화율', match: /^remote_labor_index/, note: 'Upwork 실제 의뢰 240건을 에이전트가 끝까지 해냈는지 사람이 판정. 제품(Claude Cowork, Manus, ChatGPT agent)과 기반 모델이 함께 실려 있는 유일한 독립 보드입니다.' },
        { title: 'AgentIF-OneDay (xbench) — 하루치 생활·업무·학습 과제', match: /^agentif_oneday/, note: '104개 일상 과제, 767개 채점 기준. 2025년 12월 각 제품을 직접 사용해 측정.' },
        { title: 'Mind2Web 2 · Online-Mind2Web — 웹 탐색 에이전트', match: /mind2web/, note: '실제 웹에서 정보를 찾아 답하는 과제. OpenAI 자체 측정 행은 별도 id입니다.' },
        { title: 'OpenClaw 계열 개인 비서 벤치마크 (Claw-Anything · WildClawBench)', match: /^(claw_anything|wildclawbench)/, note: '항상 켜진 개인 비서 시나리오. 모델과 하네스(OpenClaw, Claude Code, Codex, Hermes)를 바꿔 가며 측정.' },
        { title: 'ChatGPT dots 안전 평가 (GPT-6 Astra 시스템 카드 부록)', match: /^(dots_|agentic_misaligned|external_agent_board|warning_barrier|broken_search)/, note: 'OpenAI가 dots 하네스에서 직접 측정. 범위 변경 적응, 연쇄 작업에서의 권한 경계, 오해를 부르는 선제 행동, 사이버 오용 차단 등.' },
        { title: 'ChatGPT agent · Operator 출시 평가 (OpenAI)', match: /^(oai_agent|spreadsheetbench|browsecomp|hle_with_tools|frontiermath|osworld|webarena|webvoyager)/, note: 'OpenAI 시스템 카드와 출시 글의 수치. 프롬프트 인젝션 저항, 위험 작업 전 확인, 거절률 등.' },
        { title: '브라우저 에이전트 보안 (LayerX · Anthropic)', match: /^(layerx|anthropic_claude_for_chrome)/, note: 'AI 브라우저의 피싱·웹 공격 차단율(LayerX, 높을수록 좋음)과 Claude for Chrome 프롬프트 인젝션 공격 성공률(Anthropic, 낮을수록 좋음).' }
    ],
    _renderResults: function(root) {
        var self = this;
        var B = this.BOTS_DATA.benchmarks.filter(function(b) { return self._bench(b.id).length; });
        if (!B.length) return;
        var s = this._section(root, '봇·에이전트 제품 평가 결과', '제품 이름으로 공개된 점수만 모았습니다. 새로 나온 봇(Grok Bot, Muse, Gemini Spark·agent)은 아직 독립 평가가 없고, dots는 OpenAI 자체 안전 평가만 있습니다. 셀을 누르면 근거 줄이 열립니다.');
        var used = {};
        var groups = this.RESULT_GROUPS.map(function(g) { var bs = B.filter(function(b) { return !used[b.id] && g.match.test(b.id); }); bs.forEach(function(b) { used[b.id] = 1; }); return { g: g, bs: bs }; });
        var rest = B.filter(function(b) { return !used[b.id]; });
        if (rest.length) groups.push({ g: { title: '기타', note: '' }, bs: rest });
        groups.forEach(function(G) {
            if (!G.bs.length) return;
            var box = self._el('div', 'mb-8');
            box.appendChild(self._el('h3', 'text-sm font-semibold text-gray-200 mb-1', G.g.title));
            if (G.g.note) box.appendChild(self._el('p', 'text-xs text-gray-500 mb-2', G.g.note));
            var rowsSet = {};
            G.bs.forEach(function(b) { self._bench(b.id).forEach(function(r) { rowsSet[r.model_id] = 1; }); });
            var rows = Object.keys(rowsSet), first = G.bs[0].id, lf = /_lower_better$/.test(first);
            rows.sort(function(a, b) { var va = self._val(a, first), vb = self._val(b, first); if (va == null) return 1; if (vb == null) return -1; return lf ? va - vb : vb - va; });
            var w = self._el('div', 'overflow-x-auto'), t = self._el('table', 'sota-table text-xs'), th = self._el('thead'), hr = self._el('tr');
            hr.appendChild(self._el('th', null, '제품 / 모델'));
            G.bs.forEach(function(b) { var h = self._el('th', null, b.name.replace(/^OpenAI |^Anthropic /, '').slice(0, 48)); h.title = b.name + (b.description ? ' — ' + b.description : ''); h.style.minWidth = '90px'; hr.appendChild(h); });
            th.appendChild(hr); t.appendChild(th);
            var st = {};
            G.bs.forEach(function(b) { var vs = rows.map(function(m) { return self._val(m, b.id); }).filter(function(v) { return v != null; }); st[b.id] = { min: Math.min.apply(null, vs), max: Math.max.apply(null, vs), lower: /_lower_better$/.test(b.id) }; });
            var tb = self._el('tbody');
            rows.forEach(function(m) {
                var tr = self._el('tr'), tn = self._el('td', null, self._name(m)); tn.style.whiteSpace = 'nowrap'; tn.title = m;
                if (self._prod[m]) tn.style.color = self._vendorColor(self._prod[m].vendor_key); else if ((self._models[m] || {}).type === 'agent') tn.style.color = Theme.accent;
                tr.appendChild(tn);
                G.bs.forEach(function(b) {
                    var v = self._val(m, b.id), x = st[b.id];
                    var td = self._el('td', null, v == null ? '—' : (Math.abs(v) >= 100 ? v.toFixed(0) : (Math.abs(v) < 1 && v !== 0 ? v.toFixed(3) : v.toFixed(1))));
                    td.style.textAlign = 'center';
                    if (v == null) td.style.color = Theme.textDisabled;
                    else { td.style.color = self._cellColor(v, x.min, x.max, x.lower); td.style.cursor = 'pointer'; td.title = '클릭하면 근거';
                           td.addEventListener('click', function() { if (typeof Modal !== 'undefined' && Modal.showScoreSource) Modal.showScoreSource(m, b.id); }); }
                    tr.appendChild(td);
                });
                tb.appendChild(tr);
            });
            t.appendChild(tb); w.appendChild(t); box.appendChild(w);
            s.appendChild(box);
        });
    },

    _renderBenchCatalogue: function(root) {
        var self = this, B = this.BOTS_DATA.benchmarks;
        if (!B.length) return;
        var s = this._section(root, '봇·에이전트 제품용 벤치마크', '장시간·다중 앱·승인이 있는 개인/업무 에이전트를 평가하는 데이터셋과 리더보드입니다.');
        var g = this._el('div', 'grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4');
        B.forEach(function(b) {
            var c = self._el('div', 'rounded-lg border border-gray-800 p-4 space-y-1');
            c.appendChild(self._el('div', 'text-sm font-semibold text-gray-200', b.name));
            c.appendChild(self._el('p', 'text-sm text-gray-400', b.description || ''));
            c.appendChild(self._el('div', 'text-xs text-gray-500', '점수 있는 제품·모델 ' + self._bench(b.id).length + '개'));
            if (b.url) c.appendChild(self._link(b.url));
            g.appendChild(c);
        });
        s.appendChild(g);
    },

    _renderSources: function(root) {
        var self = this, S = this.BOTS_DATA.sources;
        if (!S.length) return;
        var s = this._section(root, '출처', null);
        var ul = this._el('ul', 'text-xs text-gray-400 space-y-1 list-disc pl-5');
        S.forEach(function(x) { var li = self._el('li'); li.appendChild(self._link(x.url, x.title || x.url)); if (x.what) li.appendChild(document.createTextNode(' — ' + x.what)); ul.appendChild(li); });
        s.appendChild(ul);
    }
};
